"""P08 NxTF-emulation MNIST application scaffold."""

from .config import (
    CHARACTERIZATION_TIMESTEPS,
    NUM_CLASSES,
    PRIMARY_TIMESTEPS,
    SOURCE_CHANNELS,
    SOURCE_HEIGHT,
    SOURCE_WIDTH,
    TOPOLOGY_STATUS,
    VALIDATION_SEED,
    VALIDATION_SIZE,
)

__all__ = [
    "CHARACTERIZATION_TIMESTEPS",
    "NUM_CLASSES",
    "PRIMARY_TIMESTEPS",
    "SOURCE_CHANNELS",
    "SOURCE_HEIGHT",
    "SOURCE_WIDTH",
    "TOPOLOGY_STATUS",
    "VALIDATION_SEED",
    "VALIDATION_SIZE",
]
