#!/usr/bin/env python3
"""Generate Tcl data for P04 physical two-core Python/FPGA conformance."""

from __future__ import annotations

import argparse
from pathlib import Path

from generate_p04_hls_vectors import feed_forward, recurrent_multicast
from loihi_twin_v2 import LogicalChip
from loihi_twin_v2.hardware_p03 import pack_compartment_state, pack_output_packet
from loihi_twin_v2.hardware_p04 import export_two_core_validation_image


def _hex(value: int, bits: int) -> str:
    digits = (bits + 3) // 4
    mask = (1 << bits) - 1
    return f"0x{value & mask:0{digits}X}"


def _pair_list(entries: list[tuple[int, int]], bits: int) -> str:
    return "{" + " ".join(
        "{" + f"{index} {_hex(word, bits)}" + "}" for index, word in entries
    ) + "}"


def _word_list(words: list[int], bits: int) -> str:
    return "{" + " ".join(_hex(word, bits) for word in words) + "}"


def _int_list(values: list[int] | tuple[int, ...]) -> str:
    return "{" + " ".join(str(value) for value in values) + "}"


def _trace_word(before: int, synaptic_input: int, after: int, spike: bool) -> int:
    return (
        (before & ((1 << 64) - 1))
        | ((synaptic_input & ((1 << 64) - 1)) << 64)
        | ((after & ((1 << 64) - 1)) << 128)
        | ((1 if spike else 0) << 192)
    )


def _core_image_dict(image) -> str:
    config = list(enumerate(image.config_words))
    state = list(enumerate(image.state_words))
    axons = [(seed.index, seed.word) for seed in image.axon_words]
    synapses = list(enumerate(image.synapse_words))
    route_desc = [(seed.index, seed.word) for seed in image.route_descriptor_words]
    routes = list(enumerate(image.route_words))
    return (
        "{"
        f"core_id {image.core_id} "
        f"compartment_count {image.compartment_count} "
        f"synapse_count {image.synapse_count} "
        f"route_count {image.route_count} "
        f"config_seeds {_pair_list(config, 128)} "
        f"state_seeds {_pair_list(state, 64)} "
        f"axon_seeds {_pair_list(axons, 64)} "
        f"synapse_seeds {_pair_list(synapses, 64)} "
        f"route_desc_seeds {_pair_list(route_desc, 32)} "
        f"route_seeds {_pair_list(routes, 32)}"
        "}"
    )


def build_text() -> str:
    scenarios = (feed_forward(), recurrent_multicast())
    lines = [
        "# Generated by examples/generate_p04_physical_vectors.py. Do not edit.",
        "set P04_PHYSICAL_COMPARTMENTS 16",
        "set P04_PHYSICAL_AXONS 64",
        "set P04_PHYSICAL_SYNAPSES 256",
        "set P04_PHYSICAL_ROUTES 64",
        "set P04_PHYSICAL_EVENTS 64",
        "set P04_PHYSICAL_PACKETS 64",
        "set P04_SCENARIOS {",
    ]

    for scenario in scenarios:
        image = export_two_core_validation_image(scenario.cores)
        initial_events = [[], []]
        for packet in scenario.initial_packets:
            initial_events[packet.destination_core].append(packet.destination_axon)

        chip = LogicalChip(scenario.cores)
        tick_lines: list[str] = []
        for timestep in range(scenario.ticks):
            trace = chip.step(scenario.initial_packets if timestep == 0 else ())
            core_dicts: list[str] = []
            next_events = [[], []]
            local_packets = 0
            remote_packets = 0

            for core_id in (0, 1):
                core_trace = next(c for c in trace.cores if c.logical_core_id == core_id)
                synaptic_input = [0] * len(core_trace.compartment_state_after)
                for contribution in core_trace.synaptic_contributions:
                    synaptic_input[contribution.target_compartment] += contribution.weight
                spike_set = set(core_trace.spikes_out)

                states: list[int] = []
                traces: list[int] = []
                for compartment_id in range(len(core_trace.compartment_state_after)):
                    before = pack_compartment_state(
                        core_trace.compartment_state_before[compartment_id].state
                    )
                    after = pack_compartment_state(
                        core_trace.compartment_state_after[compartment_id].state
                    )
                    states.append(after)
                    traces.append(
                        _trace_word(
                            before,
                            synaptic_input[compartment_id],
                            after,
                            compartment_id in spike_set,
                        )
                    )

                packets = [pack_output_packet(packet) for packet in core_trace.packets_out]
                for packet in core_trace.packets_out:
                    next_events[packet.destination_core].append(packet.destination_axon)
                    if packet.destination_core == core_id:
                        local_packets += 1
                    else:
                        remote_packets += 1

                core_dicts.append(
                    "{"
                    f"spike_count {len(spike_set)} "
                    f"packet_count {len(packets)} "
                    f"states {_word_list(states, 64)} "
                    f"traces {_word_list(traces, 256)} "
                    f"packets {_word_list(packets, 64)}"
                    "}"
                )

            tick_lines.append(
                "{"
                f"timestep {timestep} "
                f"core0 {core_dicts[0]} "
                f"core1 {core_dicts[1]} "
                f"next_events0 {_int_list(next_events[0])} "
                f"next_events1 {_int_list(next_events[1])} "
                f"local_packets {local_packets} "
                f"remote_packets {remote_packets}"
                "}"
            )

        lines.append(
            "    {"
            f"name {scenario.name} "
            f"core0 {_core_image_dict(image.core0)} "
            f"core1 {_core_image_dict(image.core1)} "
            f"initial_events0 {_int_list(initial_events[0])} "
            f"initial_events1 {_int_list(initial_events[1])} "
            "ticks {"
            + " ".join(tick_lines)
            + "}"
            "}"
        )

    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_text(), encoding="utf-8")
    print(
        f"P04 generated physical corpus: output={args.output} "
        "scenarios=2"
    )


if __name__ == "__main__":
    main()
