#!/usr/bin/env python3
"""Generate the deterministic P03 one-core HLS differential corpus."""

from __future__ import annotations

import argparse
from pathlib import Path

from loihi_twin_v2 import (
    CompartmentConfig,
    InputAxonBinding,
    LogicalCore,
    LogicalCoreConfig,
    OutputRoute,
    OutputRouteEntry,
    SpikePacket,
    SynapseEntry,
    SynapseTemplate,
)
from loihi_twin_v2.hardware_p03 import (
    P03_REQUIRED_ARITHMETIC,
    export_one_core_image,
    pack_compartment_state,
    pack_output_packet,
)

MAX_SEED_COMPARTMENTS = 8
MAX_SEED_EVENTS = 8
MAX_SEED_PACKETS = 8


def _config() -> LogicalCoreConfig:
    compartments = (
        CompartmentConfig(
            current_decay=4096,
            voltage_decay=4096,
            threshold=5,
            refractory_ticks=3,
        ),
        CompartmentConfig(
            current_decay=4096,
            voltage_decay=4096,
            threshold=100,
        ),
        CompartmentConfig(
            current_decay=4096,
            voltage_decay=4096,
            threshold=3,
        ),
    )
    return LogicalCoreConfig(
        core_id=0,
        compartments=compartments,
        input_axons=(
            InputAxonBinding(axon_id=10, template_id=0, target_offset=0),
            InputAxonBinding(axon_id=11, template_id=0, target_offset=1),
            InputAxonBinding(axon_id=12, template_id=1, target_offset=1),
        ),
        synapse_templates=(
            SynapseTemplate(
                template_id=0,
                entries=(
                    SynapseEntry(target_compartment=0, weight=6),
                    SynapseEntry(target_compartment=1, weight=4),
                ),
            ),
            SynapseTemplate(
                template_id=1,
                entries=(SynapseEntry(target_compartment=0, weight=-5),),
            ),
        ),
        output_routes=(
            OutputRouteEntry(
                source_compartment=0,
                routes=(OutputRoute(1, 3), OutputRoute(2, 4)),
            ),
            OutputRouteEntry(
                source_compartment=2,
                routes=(OutputRoute(3, 5),),
            ),
        ),
        arithmetic=P03_REQUIRED_ARITHMETIC,
    )


def _hex64(value: int) -> str:
    return f"0x{value & ((1 << 64) - 1):016X}ULL"


def _emit_array(values: list[int], length: int) -> str:
    padded = values + [0] * (length - len(values))
    return "{" + ", ".join(str(value) for value in padded) + "}"


def _emit_u64_array(values: list[int], length: int) -> str:
    padded = values + [0] * (length - len(values))
    return "{" + ", ".join(_hex64(value) for value in padded) + "}"


def build_text() -> str:
    config = _config()
    image = export_one_core_image(config)
    core = LogicalCore(config)

    schedule = (
        (10,),
        (11,),
        (10, 12),
        (),
        (10,),
    )

    lines: list[str] = []
    lines.append("// Generated by examples/generate_p03_hls_vectors.py. Do not edit.")
    lines.append(f"constexpr unsigned P03_SEED_COMPARTMENT_COUNT = {image.compartment_count};")
    lines.append(f"constexpr unsigned P03_SEED_SYNAPSE_COUNT = {image.synapse_count};")
    lines.append(f"constexpr unsigned P03_SEED_ROUTE_COUNT = {image.route_count};")
    lines.append("")

    lines.append("const Word128Seed P03_CONFIG_SEEDS[] = {")
    for index, word in enumerate(image.config_words):
        lines.append(
            f"    {{{index}, {_hex64(word)}, {_hex64(word >> 64)}}},"
        )
    lines.append("};")
    lines.append("constexpr unsigned P03_CONFIG_SEED_COUNT = sizeof(P03_CONFIG_SEEDS) / sizeof(P03_CONFIG_SEEDS[0]);")
    lines.append("")

    lines.append("const Word64Seed P03_STATE_SEEDS[] = {")
    for index, word in enumerate(image.state_words):
        lines.append(f"    {{{index}, {_hex64(word)}}},")
    lines.append("};")
    lines.append("constexpr unsigned P03_STATE_SEED_COUNT = sizeof(P03_STATE_SEEDS) / sizeof(P03_STATE_SEEDS[0]);")
    lines.append("")

    lines.append("const Word64Seed P03_AXON_SEEDS[] = {")
    for seed in image.axon_words:
        lines.append(f"    {{{seed.index}, {_hex64(seed.word)}}},")
    lines.append("};")
    lines.append("constexpr unsigned P03_AXON_SEED_COUNT = sizeof(P03_AXON_SEEDS) / sizeof(P03_AXON_SEEDS[0]);")
    lines.append("")

    lines.append("const Word64Seed P03_SYNAPSE_SEEDS[] = {")
    for index, word in enumerate(image.synapse_words):
        lines.append(f"    {{{index}, {_hex64(word)}}},")
    lines.append("};")
    lines.append("constexpr unsigned P03_SYNAPSE_SEED_COUNT = sizeof(P03_SYNAPSE_SEEDS) / sizeof(P03_SYNAPSE_SEEDS[0]);")
    lines.append("")

    lines.append("const Word32Seed P03_ROUTE_DESC_SEEDS[] = {")
    for seed in image.route_descriptor_words:
        lines.append(f"    {{{seed.index}, 0x{seed.word & 0xFFFFFFFF:08X}u}},")
    lines.append("};")
    lines.append("constexpr unsigned P03_ROUTE_DESC_SEED_COUNT = sizeof(P03_ROUTE_DESC_SEEDS) / sizeof(P03_ROUTE_DESC_SEEDS[0]);")
    lines.append("")

    lines.append("const Word32Seed P03_ROUTE_SEEDS[] = {")
    for index, word in enumerate(image.route_words):
        lines.append(f"    {{{index}, 0x{word & 0xFFFFFFFF:08X}u}},")
    lines.append("};")
    lines.append("constexpr unsigned P03_ROUTE_SEED_COUNT = sizeof(P03_ROUTE_SEEDS) / sizeof(P03_ROUTE_SEEDS[0]);")
    lines.append("")

    lines.append("const TickSeed P03_TICKS[] = {")
    for timestep, events in enumerate(schedule):
        for axon_id in events:
            core.ingest_packet(
                SpikePacket(
                    target_timestep=timestep,
                    destination_core=0,
                    destination_axon=axon_id,
                )
            )
        trace = core.evaluate(timestep)
        synaptic_input = [0] * image.compartment_count
        for contribution in trace.synaptic_contributions:
            synaptic_input[contribution.target_compartment] += contribution.weight
        spike_set = set(trace.spikes_out)

        expected_entries: list[str] = []
        for compartment_id in range(MAX_SEED_COMPARTMENTS):
            if compartment_id < image.compartment_count:
                before = pack_compartment_state(
                    trace.compartment_state_before[compartment_id].state
                )
                after = pack_compartment_state(
                    trace.compartment_state_after[compartment_id].state
                )
                expected_entries.append(
                    "{" + ", ".join(
                        (
                            _hex64(before),
                            str(synaptic_input[compartment_id]),
                            _hex64(after),
                            "1" if compartment_id in spike_set else "0",
                        )
                    ) + "}"
                )
            else:
                expected_entries.append("{0ULL, 0, 0ULL, 0}")

        packets = [pack_output_packet(packet) for packet in trace.packets_out]
        lines.append("    {")
        lines.append(f"        {timestep}, {len(events)}, {_emit_array(list(events), MAX_SEED_EVENTS)},")
        lines.append("        {" + ", ".join(expected_entries) + "},")
        lines.append(f"        {len(packets)}, {_emit_u64_array(packets, MAX_SEED_PACKETS)}")
        lines.append("    },")
    lines.append("};")
    lines.append("constexpr unsigned P03_TICK_COUNT = sizeof(P03_TICKS) / sizeof(P03_TICKS[0]);")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    text = build_text()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(
        f"P03 generated HLS corpus: output={args.output} "
        f"ticks=5 compartments=3"
    )


if __name__ == "__main__":
    main()
