from __future__ import annotations

import argparse
from pathlib import Path

from neuromorphic_twin.fpga_core_capacity import (
    pack_neuron_config_word,
    pack_neuron_state_word,
)
from neuromorphic_twin.fpga_synapse_reference import accumulate_frozen_weight_image_v1
from neuromorphic_twin.fpga_weight_storage import (
    FrozenWeightStorage,
    pack_synapse_word,
    pack_weight_format,
)
from neuromorphic_twin.hls_conformance import directed_hls_neuron_vectors
from neuromorphic_twin.model import NeuronConfig, NeuronState
from neuromorphic_twin.neuron_array_reference import step_packed_neuron_array_v1
from neuromorphic_twin.weights import WeightFormat, WeightSignMode

M11_5_3_INTEGRATED_NEURONS = 16
M11_5_3_INTEGRATED_SEED_TAG = 0x4D353349  # "M53I" evidence tag


def _storage() -> FrozenWeightStorage:
    formats = (
        WeightFormat(exponent=0, num_weight_bits=8, sign_mode=WeightSignMode.EXCITATORY),
        WeightFormat(exponent=0, num_weight_bits=8, sign_mode=WeightSignMode.INHIBITORY),
        WeightFormat(exponent=0, num_weight_bits=8, sign_mode=WeightSignMode.MIXED),
        WeightFormat(exponent=7, num_weight_bits=8, sign_mode=WeightSignMode.EXCITATORY),
        WeightFormat(exponent=7, num_weight_bits=8, sign_mode=WeightSignMode.INHIBITORY),
        WeightFormat(exponent=-3, num_weight_bits=8, sign_mode=WeightSignMode.MIXED),
    )
    rows = (
        ((0, 2, 0), (1, -3, 1)),
        ((2, 5, 2), (3, 255, 3)),
        ((4, -256, 4), (5, -5, 5)),
        ((6, 17, 0), (7, -9, 1)),
        ((8, 31, 2), (9, 1, 0)),
        ((10, 200, 0),),
        ((11, -200, 1), (12, -127, 2)),
        ((13, 33, 0), (14, -17, 1), (15, 63, 2)),
    )
    synapse_words: list[int] = []
    pointers = [0]
    for row in rows:
        for target, mantissa, format_index in row:
            synapse_words.append(
                pack_synapse_word(
                    target_neuron=target,
                    requested_mantissa=mantissa,
                    format_index=format_index,
                )
            )
        pointers.append(len(synapse_words))
    return FrozenWeightStorage(
        format_words=tuple(pack_weight_format(fmt) for fmt in formats),
        synapse_words=tuple(synapse_words),
        axon_row_pointers=tuple(pointers),
    )


def integrated_vectors() -> dict[str, object]:
    vectors = directed_hls_neuron_vectors()[:M11_5_3_INTEGRATED_NEURONS]
    storage = _storage()
    external_axons = (0, 1, 2, 3, 4, 5, 6, 7, 0, 3, 7)
    recurrent_axons = (2, 6, 1, 5, 5, 7)

    config_words: list[int] = []
    initial_state_words: list[int] = []
    reset_state_words: list[int] = []
    for vector in vectors:
        config = NeuronConfig(
            current_decay=vector.current_decay,
            voltage_decay=vector.voltage_decay,
            threshold=vector.threshold,
            bias=vector.bias,
            reset_voltage=vector.reset_voltage,
            refractory_ticks=vector.refractory_ticks,
        )
        state = NeuronState(
            current=vector.current_before,
            voltage=vector.voltage_before,
            refractory_remaining=vector.refractory_before,
        )
        config_words.append(pack_neuron_config_word(config))
        initial_state_words.append(pack_neuron_state_word(state))
        reset_state_words.append(
            pack_neuron_state_word(
                NeuronState(current=0, voltage=config.reset_voltage, refractory_remaining=0)
            )
        )

    phase_b = accumulate_frozen_weight_image_v1(
        storage,
        neuron_count=M11_5_3_INTEGRATED_NEURONS,
        external_axons=external_axons,
        recurrent_axons=recurrent_axons,
    )
    expected = step_packed_neuron_array_v1(
        initial_state_words,
        config_words,
        phase_b.accumulators,
    )
    return {
        "storage": storage,
        "external_axons": external_axons,
        "recurrent_axons": recurrent_axons,
        "config_words": tuple(config_words),
        "initial_state_words": tuple(initial_state_words),
        "reset_state_words": tuple(reset_state_words),
        "expected_accumulators": phase_b.accumulators,
        "expected_state_words": expected.state_words,
        "expected_spikes": tuple(int(value) for value in expected.spikes),
    }


def _hex(value: int, width: int) -> str:
    return f"{value & ((1 << width) - 1):0{(width + 3) // 4}x}"


def write_systemverilog_include(output: Path) -> Path:
    values = integrated_vectors()
    storage = values["storage"]
    assert isinstance(storage, FrozenWeightStorage)
    external = values["external_axons"]
    recurrent = values["recurrent_axons"]
    assert isinstance(external, tuple)
    assert isinstance(recurrent, tuple)

    lines = [
        "// Generated by examples/generate_m11_5_3_integrated_vectors.py; do not edit.",
        f"localparam int M11_5_3I_NEURON_COUNT = {M11_5_3_INTEGRATED_NEURONS};",
        f"localparam int M11_5_3I_AXON_COUNT = {storage.axon_count};",
        f"localparam int M11_5_3I_SYNAPSE_COUNT = {storage.synapse_count};",
        f"localparam int M11_5_3I_FORMAT_COUNT = {storage.format_count};",
        f"localparam int M11_5_3I_EXTERNAL_COUNT = {len(external)};",
        f"localparam int M11_5_3I_RECURRENT_COUNT = {len(recurrent)};",
        f"localparam logic [31:0] M11_5_3I_TAG = 32'h{M11_5_3_INTEGRATED_SEED_TAG:08x};",
        "",
    ]

    def emit(name: str, width: int, words: tuple[int, ...], signed: bool = False) -> None:
        sign = " signed" if signed else ""
        lines.append(f"localparam logic{sign} [{width - 1}:0] {name} [0:{len(words) - 1}] = '{{")
        for index, word in enumerate(words):
            comma = "," if index + 1 != len(words) else ""
            lines.append(f"    {width}'h{_hex(word, width)}{comma}")
        lines.append("};")
        lines.append("")

    emit("M11_5_3I_FORMAT_WORDS", 16, storage.format_words)
    emit("M11_5_3I_SYNAPSE_WORDS", 32, storage.synapse_words)
    emit("M11_5_3I_ROW_POINTERS", 32, storage.axon_row_pointers)
    emit("M11_5_3I_EXTERNAL_EVENTS", 16, external)
    emit("M11_5_3I_RECURRENT_EVENTS", 16, recurrent)
    emit("M11_5_3I_CONFIG_WORDS", 128, values["config_words"])
    emit("M11_5_3I_INITIAL_STATE_WORDS", 64, values["initial_state_words"])
    emit("M11_5_3I_RESET_STATE_WORDS", 64, values["reset_state_words"])
    emit("M11_5_3I_EXPECTED_ACCUMULATORS", 64, values["expected_accumulators"], signed=True)
    emit("M11_5_3I_EXPECTED_STATE_WORDS", 64, values["expected_state_words"])
    emit("M11_5_3I_EXPECTED_SPIKES", 1, values["expected_spikes"])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    output = write_systemverilog_include(args.output)
    values = integrated_vectors()
    storage = values["storage"]
    assert isinstance(storage, FrozenWeightStorage)
    print(
        "M11.5.3 integrated vectors generated: "
        f"neurons={M11_5_3_INTEGRATED_NEURONS}, axons={storage.axon_count}, "
        f"synapses={storage.synapse_count}, formats={storage.format_count}, "
        f"tag=0x{M11_5_3_INTEGRATED_SEED_TAG:08X}"
    )
    print(f"output={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
