from __future__ import annotations

import argparse
from pathlib import Path

from neuromorphic_twin.fpga_broad_regression import (
    M12_BROAD_GENERATOR_VERSION,
    M12_BROAD_MASTER_SEED,
    build_m12_broad_cases,
    write_m12_broad_corpus,
)


def _hex(value: int, width: int) -> str:
    return f"{value & ((1 << width) - 1):0{(width + 3) // 4}x}"


def write_systemverilog_include(output: Path) -> Path:
    """Write packed FPGA inputs only; all Python-golden outputs remain host-side."""

    cases = build_m12_broad_cases()
    workloads = [case.workload for case in cases]

    config_offsets: list[int] = []
    config_words: list[int] = []
    state_offsets: list[int] = []
    state_words: list[int] = []
    format_offsets: list[int] = []
    format_words: list[int] = []
    synapse_offsets: list[int] = []
    synapse_words: list[int] = []
    weight_row_offsets: list[int] = []
    weight_rows: list[int] = []
    route_row_offsets: list[int] = []
    route_rows: list[int] = []
    route_target_offsets: list[int] = []
    route_targets: list[int] = []
    case_tick_bases: list[int] = []
    external_tick_offsets: list[int] = []
    external_counts: list[int] = []
    external_events: list[int] = []

    for workload in workloads:
        config_offsets.append(len(config_words))
        config_words.extend(workload.config_words)
        state_offsets.append(len(state_words))
        state_words.extend(workload.initial_state_words)
        format_offsets.append(len(format_words))
        format_words.extend(workload.storage.format_words)
        synapse_offsets.append(len(synapse_words))
        synapse_words.extend(workload.storage.synapse_words)
        weight_row_offsets.append(len(weight_rows))
        weight_rows.extend(workload.storage.axon_row_pointers)
        route_row_offsets.append(len(route_rows))
        route_rows.extend(workload.routes.row_pointers)
        route_target_offsets.append(len(route_targets))
        route_targets.extend(workload.routes.target_axons)

        case_tick_bases.append(len(external_counts))
        for events in workload.external_schedule:
            external_tick_offsets.append(len(external_events))
            external_counts.append(len(events))
            external_events.extend(events)

    lines = [
        "// Generated by examples/generate_m12_4_broad_corpus.py; do not edit.",
        "// INPUTS ONLY: static load images and per-tick external events.",
        "// Recurrent traffic must be generated by the FPGA itself; golden outputs stay host-side.",
        f"localparam int M12_4_CASE_COUNT = {len(cases)};",
        f"localparam int M12_4_TOTAL_TICKS = {sum(case.tick_count for case in cases)};",
        f"localparam logic [63:0] M12_4_MASTER_SEED = 64'h{M12_BROAD_MASTER_SEED:016x};",
        "",
    ]

    def emit(name: str, width: int, words: list[int] | tuple[int, ...]) -> None:
        values = list(words)
        if not values:
            values = [0]
        lines.append(f"localparam logic [{width - 1}:0] {name} [0:{len(values) - 1}] = '{{")
        for index, word in enumerate(values):
            comma = "," if index + 1 != len(values) else ""
            lines.append(f"    {width}'h{_hex(word, width)}{comma}")
        lines.append("};")
        lines.append("")

    emit("M12_4_NEURON_COUNTS", 9, [w.neuron_count for w in workloads])
    emit("M12_4_AXON_COUNTS", 11, [w.storage.axon_count for w in workloads])
    emit("M12_4_SYNAPSE_COUNTS", 13, [w.storage.synapse_count for w in workloads])
    emit("M12_4_FORMAT_COUNTS", 5, [w.storage.format_count for w in workloads])
    emit("M12_4_ROUTE_COUNTS", 13, [w.routes.route_count for w in workloads])
    emit("M12_4_TICK_COUNTS", 8, [w.tick_count for w in workloads])

    emit("M12_4_CONFIG_OFFSETS", 32, config_offsets)
    emit("M12_4_CONFIG_WORDS", 128, config_words)
    emit("M12_4_STATE_OFFSETS", 32, state_offsets)
    emit("M12_4_INITIAL_STATE_WORDS", 64, state_words)
    emit("M12_4_FORMAT_OFFSETS", 32, format_offsets)
    emit("M12_4_FORMAT_WORDS", 16, format_words)
    emit("M12_4_SYNAPSE_OFFSETS", 32, synapse_offsets)
    emit("M12_4_SYNAPSE_WORDS", 32, synapse_words)
    emit("M12_4_WEIGHT_ROW_OFFSETS", 32, weight_row_offsets)
    emit("M12_4_WEIGHT_ROWS", 32, weight_rows)
    emit("M12_4_ROUTE_ROW_OFFSETS", 32, route_row_offsets)
    emit("M12_4_ROUTE_ROWS", 32, route_rows)
    emit("M12_4_ROUTE_TARGET_OFFSETS", 32, route_target_offsets)
    emit("M12_4_ROUTE_TARGETS", 16, route_targets)
    emit("M12_4_CASE_TICK_BASES", 32, case_tick_bases)
    emit("M12_4_EXTERNAL_TICK_OFFSETS", 32, external_tick_offsets)
    emit("M12_4_EXTERNAL_COUNTS", 13, external_counts)
    emit("M12_4_EXTERNAL_EVENTS", 16, external_events)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def write_hardware_case_metadata(output: Path) -> Path:
    cases = build_m12_broad_cases()
    lines = [
        "case_id\tcase_name\tsource_kind\tseed\tconfiguration_sha256\tneuron_count\taxon_count\tsynapse_count\troute_count\ttick_count"
    ]
    for case in cases:
        w = case.workload
        lines.append(
            f"{case.case_id}\t{case.name}\t{case.source_kind}\t0x{case.seed:016x}\t"
            f"{case.configuration_sha256}\t{w.neuron_count}\t{w.storage.axon_count}\t"
            f"{w.storage.synapse_count}\t{w.routes.route_count}\t{w.tick_count}"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate M12.4 deterministic broad-regression FPGA inputs and Python golden timelines."
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--sv-output", type=Path, required=True)
    args = parser.parse_args()

    manifest = write_m12_broad_corpus(args.output_dir)
    include = write_systemverilog_include(args.sv_output)
    metadata = write_hardware_case_metadata(args.output_dir / "hardware_cases.tsv")
    cases = build_m12_broad_cases()
    print(
        "M12.4 broad deterministic corpus generated: "
        f"version={M12_BROAD_GENERATOR_VERSION} cases={len(cases)} "
        f"ticks={sum(case.tick_count for case in cases)} "
        f"manifest={manifest} metadata={metadata} sv={include}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
