#!/usr/bin/env python3
"""Generate deterministic packed multi-neuron vectors for M11.5.2 RTL/HLS integration."""

from __future__ import annotations

import argparse
from pathlib import Path

from neuromorphic_twin.fpga_core_capacity import (
    pack_neuron_config_word,
    pack_neuron_state_word,
)
from neuromorphic_twin.hls_conformance import (
    M11_2_DEFAULT_SEED,
    directed_hls_neuron_vectors,
    randomized_hls_neuron_vectors,
)
from neuromorphic_twin.model import NeuronConfig, NeuronState


M11_5_2_RANDOM_CASES = 40
M11_5_2_NEURON_COUNT = len(directed_hls_neuron_vectors()) + M11_5_2_RANDOM_CASES


def _hex(value: int, bits: int) -> str:
    digits = (bits + 3) // 4
    return f"{value & ((1 << bits) - 1):0{digits}x}"


def build_vectors() -> tuple[object, ...]:
    """Use all M11.2 directed cases plus 40 deterministic random cases."""

    return directed_hls_neuron_vectors() + randomized_hls_neuron_vectors(
        count=M11_5_2_RANDOM_CASES,
        seed=M11_2_DEFAULT_SEED,
    )


def write_systemverilog_include(output_path: str | Path) -> Path:
    vectors = build_vectors()
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    config_words: list[int] = []
    initial_state_words: list[int] = []
    reset_state_words: list[int] = []
    accum_words: list[int] = []
    expected_state_words: list[int] = []
    expected_spikes: list[int] = []

    for vector in vectors:
        config = NeuronConfig(
            current_decay=vector.current_decay,
            voltage_decay=vector.voltage_decay,
            threshold=vector.threshold,
            bias=vector.bias,
            reset_voltage=vector.reset_voltage,
            refractory_ticks=vector.refractory_ticks,
        )
        initial_state = NeuronState(
            current=vector.current_before,
            voltage=vector.voltage_before,
            refractory_remaining=vector.refractory_before,
        )
        reset_state = NeuronState(
            current=0,
            voltage=vector.reset_voltage,
            refractory_remaining=0,
        )
        expected_state = NeuronState(
            current=vector.expected_current,
            voltage=vector.expected_voltage,
            refractory_remaining=vector.expected_refractory,
        )

        config_words.append(pack_neuron_config_word(config))
        initial_state_words.append(pack_neuron_state_word(initial_state))
        reset_state_words.append(pack_neuron_state_word(reset_state))
        accum_words.append(vector.synaptic_input)
        expected_state_words.append(pack_neuron_state_word(expected_state))
        expected_spikes.append(vector.expected_spike)

    lines = [
        "// Generated by examples/generate_m11_5_2_vectors.py; do not edit.",
        f"localparam int M11_5_2_NEURON_COUNT = {len(vectors)};",
        f"localparam logic [31:0] M11_5_2_SEED = 32'h{M11_2_DEFAULT_SEED:08x};",
        "",
    ]

    def emit_array(name: str, width: int, words: list[int], signed: bool = False) -> None:
        sign = " signed" if signed else ""
        lines.append(
            f"localparam logic{sign} [{width - 1}:0] {name} [0:M11_5_2_NEURON_COUNT-1] = '{{"
        )
        for index, word in enumerate(words):
            comma = "," if index + 1 != len(words) else ""
            comment = f" // {vectors[index].name}"
            lines.append(f"    {width}'h{_hex(word, width)}{comma}{comment}")
        lines.append("};")
        lines.append("")

    emit_array("M11_5_2_CONFIG_WORDS", 128, config_words)
    emit_array("M11_5_2_INITIAL_STATE_WORDS", 64, initial_state_words)
    emit_array("M11_5_2_RESET_STATE_WORDS", 64, reset_state_words)
    emit_array("M11_5_2_ACCUM_WORDS", 64, accum_words, signed=True)
    emit_array("M11_5_2_EXPECTED_STATE_WORDS", 64, expected_state_words)

    lines.append(
        "localparam logic M11_5_2_EXPECTED_SPIKES [0:M11_5_2_NEURON_COUNT-1] = '{"
    )
    for index, spike in enumerate(expected_spikes):
        comma = "," if index + 1 != len(expected_spikes) else ""
        lines.append(f"    1'b{spike}{comma} // {vectors[index].name}")
    lines.append("};")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    output = write_systemverilog_include(args.output)
    print(
        "M11.5.2 packed integration vectors generated: "
        f"neurons={M11_5_2_NEURON_COUNT}, directed=24, random={M11_5_2_RANDOM_CASES}, "
        f"seed=0x{M11_2_DEFAULT_SEED:08X}"
    )
    print(f"output={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
