"""Phase-1 neuromorphic digital-twin reference model."""

from .arithmetic import ArithmeticConfig, OverflowMode, round_away_from_zero
from .core import NeuromorphicCore
from .fpga_weight_storage import (
    AXON_ROW_POINTER_BITS,
    FORMAT_WORD_BITS,
    FPGA_WEIGHT_STORAGE_SCHEMA,
    MAX_WEIGHT_FORMATS,
    SYNAPSE_WORD_BITS,
    FrozenWeightStorage,
    PackedSynapseFields,
    WeightStorageArtifacts,
    WeightStorageEstimate,
    estimate_weight_storage,
    freeze_encoded_synapses,
    pack_synapse_word,
    pack_weight_format,
    read_weight_storage_json,
    unpack_synapse_word,
    unpack_weight_format,
    write_weight_storage_image,
)
from .model import NeuronConfig, NeuronState, Spike, SpikeRoute, Synapse, TickTrace
from .neuron import step_neuron
from .specification import (
    CORE_SPEC_SCHEMA,
    DECAY_BITS,
    DECAY_MAX,
    DECAY_MIN,
    FPGA_CORE_ARITHMETIC_V1,
    ID_BITS,
    ID_MAX,
    REFRACTORY_BITS,
    REFRACTORY_MAX,
    STATE_BITS,
    STATE_MAX,
    STATE_MIN,
    TICK_BITS,
    validate_core_configuration_v1,
    validate_input_axons_v1,
    validate_neuron_config_v1,
    validate_neuron_state_v1,
    validate_spike_route_v1,
    validate_synapse_v1,
)
from .weights import (
    StaticWeightEncoding,
    WeightFormat,
    WeightSignMode,
    encode_static_weight,
)

__all__ = [
    "AXON_ROW_POINTER_BITS",
    "ArithmeticConfig",
    "CORE_SPEC_SCHEMA",
    "DECAY_BITS",
    "DECAY_MAX",
    "DECAY_MIN",
    "FORMAT_WORD_BITS",
    "FPGA_CORE_ARITHMETIC_V1",
    "FPGA_WEIGHT_STORAGE_SCHEMA",
    "FrozenWeightStorage",
    "ID_BITS",
    "ID_MAX",
    "MAX_WEIGHT_FORMATS",
    "NeuronConfig",
    "NeuronState",
    "NeuromorphicCore",
    "OverflowMode",
    "PackedSynapseFields",
    "REFRACTORY_BITS",
    "REFRACTORY_MAX",
    "STATE_BITS",
    "STATE_MAX",
    "STATE_MIN",
    "SYNAPSE_WORD_BITS",
    "Spike",
    "SpikeRoute",
    "StaticWeightEncoding",
    "Synapse",
    "TICK_BITS",
    "TickTrace",
    "WeightFormat",
    "WeightSignMode",
    "WeightStorageArtifacts",
    "WeightStorageEstimate",
    "encode_static_weight",
    "estimate_weight_storage",
    "freeze_encoded_synapses",
    "pack_synapse_word",
    "pack_weight_format",
    "read_weight_storage_json",
    "round_away_from_zero",
    "step_neuron",
    "unpack_synapse_word",
    "unpack_weight_format",
    "validate_core_configuration_v1",
    "validate_input_axons_v1",
    "validate_neuron_config_v1",
    "validate_neuron_state_v1",
    "validate_spike_route_v1",
    "validate_synapse_v1",
    "write_weight_storage_image",
]
