"""Data structures shared by the neuron and core models."""

from __future__ import annotations

from dataclasses import dataclass


DECAY_SCALE = 4096


@dataclass(frozen=True, slots=True)
class NeuronConfig:
    """Configuration registers for one current-based LIF neuron.

    Decay values are integer fractions of 4096:
        0    -> no decay
        4096 -> full decay in one algorithmic tick

    The current Phase-1 reset model sets voltage to `reset_voltage` after a
    spike. This is intentionally simple and can later be replaced by a profile
    that reproduces a specific neuromorphic chip.
    """

    current_decay: int
    voltage_decay: int
    threshold: int
    bias: int = 0
    reset_voltage: int = 0
    refractory_ticks: int = 0

    def __post_init__(self) -> None:
        for name, value in (
            ("current_decay", self.current_decay),
            ("voltage_decay", self.voltage_decay),
        ):
            if not 0 <= value <= DECAY_SCALE:
                raise ValueError(f"{name} must be in [0, {DECAY_SCALE}]")
        if self.threshold <= self.reset_voltage:
            raise ValueError("threshold must be greater than reset_voltage")
        if self.refractory_ticks < 0:
            raise ValueError("refractory_ticks cannot be negative")


@dataclass(frozen=True, slots=True)
class NeuronState:
    """Runtime state registers for one neuron."""

    current: int = 0
    voltage: int = 0
    refractory_remaining: int = 0

    def __post_init__(self) -> None:
        if self.refractory_remaining < 0:
            raise ValueError("refractory_remaining cannot be negative")


@dataclass(frozen=True, slots=True)
class Synapse:
    """One fixed-weight connection from an input axon to a target neuron."""

    axon_id: int
    target_neuron: int
    weight: int

    def __post_init__(self) -> None:
        if self.axon_id < 0:
            raise ValueError("axon_id cannot be negative")
        if self.target_neuron < 0:
            raise ValueError("target_neuron cannot be negative")


@dataclass(frozen=True, slots=True)
class Spike:
    """An output spike generated by a neuron at one algorithmic tick."""

    tick: int
    neuron_id: int


@dataclass(frozen=True, slots=True)
class TickTrace:
    """Complete observable state transition for one core tick.

    Tuples are used so a returned trace cannot change after the simulator moves
    on to later ticks. That makes traces safe regression-test artifacts.
    """

    tick: int
    input_axons: tuple[int, ...]
    synaptic_input: tuple[int, ...]
    current_before: tuple[int, ...]
    voltage_before: tuple[int, ...]
    current_after: tuple[int, ...]
    voltage_after: tuple[int, ...]
    refractory_after: tuple[int, ...]
    spikes: tuple[Spike, ...]
