from __future__ import annotations

import argparse
import json
from pathlib import Path

from mnist_app.brian2loihi_matched import (
    run_brian2loihi_matched_case,
    summarize_suite,
    write_case_result,
)
from mnist_app.matched_bundle import read_matched_request_bundle
from mnist_app.matched_reference import (
    load_frozen_matched_workload,
    semantic_audit_payload,
)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run the frozen native-sparse MNIST workload against pinned Brian2Loihi."
    )
    parser.add_argument(
        "--bundle",
        type=Path,
        help="Bundle generated by prepare_matched_reference_bundle.py. Omit with --audit-only.",
    )
    parser.add_argument("--audit-only", action="store_true")
    parser.add_argument(
        "--frozen-root",
        type=Path,
        default=Path("applications/mnist/frozen/mnist-v1"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("applications/mnist/build/mnist-11/brian2loihi"),
    )
    args = parser.parse_args()
    if not args.audit_only and args.bundle is None:
        parser.error("--bundle is required unless --audit-only is selected")

    workload = load_frozen_matched_workload(args.frozen_root)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    audit_path = args.output_dir / "semantic_audit.json"
    audit_path.write_text(
        json.dumps(semantic_audit_payload(workload), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        "MNIST-11 semantic preflight: profile=native-sparse neurons=10 axons=784 "
        f"synapses={len(workload.synapses)} threshold={workload.configs[0].threshold} "
        f"sat24_bound={workload.conservative_abs_voltage_bound:.1f} audit={audit_path}"
    )
    if args.audit_only:
        return 0

    cases = read_matched_request_bundle(args.bundle)
    results: list[dict[str, object]] = []
    for case in cases:
        result = run_brian2loihi_matched_case(workload, case)
        results.append(result)
        path = args.output_dir / f"index{case.mnist_test_index:05d}.json"
        write_case_result(result, path)
        trace = result["trace_comparison"]
        print(
            f"MNIST-11 case index={case.mnist_test_index} label={case.label} "
            f"project={result['project_prediction']} brian={result['brian2loihi_prediction']} "
            f"trace_mismatches={trace['mismatch_count']} "
            f"weight_mismatches={result['effective_weight_mismatch_count']} "
            f"passed={result['passed']}"
        )

    suite = summarize_suite(results)
    suite_path = args.output_dir / "suite.json"
    suite_path.write_text(json.dumps(suite, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        f"MNIST-11 suite: cases={suite['case_count']} passed={suite['passed_cases']} "
        f"prediction_agreement={suite['prediction_agreement_cases']} "
        f"spike_vector_agreement={suite['spike_count_vector_agreement_cases']} "
        f"exact_trace={suite['exact_trace_agreement_cases']} all_passed={suite['all_passed']}"
    )
    print(f"suite: {suite_path}")
    return 0 if suite["all_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
