`timescale 1ns/1ps

// M11.5.4.4 full-tick composition.
//
// The already-verified M11.5.3 core remains unchanged. Before each algorithmic
// tick this wrapper copies the recurrent router's current-bank prefix into the
// Phase-B recurrent-event buffer. After the real-HLS neuron phase completes, it
// scans committed spike flags into the route engine and starts Phase E/F. The
// route bank can swap only after Phase C is complete, so recurrence generated by
// tick t cannot be consumed until a later tick_start (tick t+1).
module recurrent_integrated_core_controller_v1 #(
    parameter integer MAX_NEURONS  = 256,
    parameter integer MAX_AXONS    = 1024,
    parameter integer MAX_SYNAPSES = 4096,
    parameter integer MAX_FORMATS  = 16,
    parameter integer MAX_ROUTES   = 4096,
    parameter integer MAX_EVENTS   = 4096
) (
    input  logic         ap_clk,
    input  logic         ap_rst,

    input  logic         core_reset_start,
    input  logic         tick_start,
    input  logic [8:0]   neuron_count,
    input  logic [10:0]  axon_count,
    input  logic [12:0]  synapse_count,
    input  logic [4:0]   format_count,
    input  logic [12:0]  external_event_count,
    input  logic [12:0]  route_count,

    output logic         busy,
    output logic         core_reset_done,
    output logic         tick_done,
    output logic [31:0]  tick,
    output logic         fault,
    output logic [7:0]   fault_code,
    output logic [7:0]   active_neuron,
    output logic         recurrent_current_bank,
    output logic [12:0]  recurrent_current_count,
    output logic [12:0]  last_consumed_recurrent_count,
    output logic [12:0]  last_routed_count,
    output logic [12:0]  trace_external_event_count,

    // Neuron and frozen M08 preload paths.
    input  logic         config_we,
    input  logic [7:0]   config_addr,
    input  logic [127:0] config_wdata,
    input  logic         state_we,
    input  logic [7:0]   state_addr,
    input  logic [63:0]  state_wdata,
    input  logic         format_we,
    input  logic [3:0]   format_addr,
    input  logic [15:0]  format_wdata,
    input  logic         synapse_we,
    input  logic [11:0]  synapse_addr,
    input  logic [31:0]  synapse_wdata,
    input  logic         row_we,
    input  logic [10:0]  row_addr,
    input  logic [31:0]  row_wdata,
    input  logic         external_we,
    input  logic [11:0]  external_addr,
    input  logic [15:0]  external_wdata,

    // Frozen recurrent route CSR preload.
    input  logic         route_row_we,
    input  logic [8:0]   route_row_addr,
    input  logic [31:0]  route_row_wdata,
    input  logic         route_target_we,
    input  logic [11:0]  route_target_addr,
    input  logic [15:0]  route_target_wdata,

    // Post-Phase-F neuron/Phase-B trace visibility. The public validity pulse is
    // suppressed while the outer recurrent controller is busy, including the
    // internal spike-read phase after the inner neuron tick completes.
    input  logic         debug_re,
    input  logic [7:0]   debug_addr,
    output logic         debug_rvalid,
    output logic [127:0] debug_config_rdata,
    output logic [63:0]  debug_state_before_rdata,
    output logic [63:0]  debug_state_rdata,
    output logic signed [63:0] debug_synaptic_input_rdata,
    output logic signed [63:0] debug_accum_rdata,
    output logic         debug_spike_rdata,

    // External-event trace readback from the Phase-B memory consumed on the
    // completed tick. Valid only while the outer core is idle.
    input  logic         external_debug_re,
    input  logic [11:0]  external_debug_addr,
    output logic         external_debug_rvalid,
    output logic [15:0]  external_debug_rdata,

    // Recurrent-bank debug visibility while the full core is idle. After Phase
    // F, the new current bank is routed_output_axons; the opposite bank prefix
    // of last_consumed_recurrent_count is recurrent_input_axons.
    input  logic         recurrent_debug_re,
    input  logic         recurrent_debug_bank,
    input  logic [11:0]  recurrent_debug_addr,
    output logic         recurrent_debug_rvalid,
    output logic [15:0]  recurrent_debug_rdata,
    output logic [12:0]  recurrent_bank0_count,
    output logic [12:0]  recurrent_bank1_count,

    // Scalar connection to packaged neuron_step_v1.
    output logic         hls_ap_start,
    input  logic         hls_ap_done,
    input  logic         hls_ap_idle,
    input  logic         hls_ap_ready,
    output logic signed [23:0] hls_current_before,
    output logic signed [23:0] hls_voltage_before,
    output logic        [15:0] hls_refractory_before,
    output logic signed [63:0] hls_synaptic_input,
    output logic        [12:0] hls_current_decay,
    output logic        [12:0] hls_voltage_decay,
    output logic signed [23:0] hls_threshold,
    output logic signed [23:0] hls_bias,
    output logic signed [23:0] hls_reset_voltage,
    output logic        [15:0] hls_refractory_ticks,
    input  logic signed [23:0] hls_current_after,
    input  logic                hls_current_after_ap_vld,
    input  logic signed [23:0] hls_voltage_after,
    input  logic                hls_voltage_after_ap_vld,
    input  logic        [15:0] hls_refractory_after,
    input  logic                hls_refractory_after_ap_vld,
    input  logic                hls_spiked,
    input  logic                hls_spiked_ap_vld
);

    localparam logic [7:0] FAULT_NONE            = 8'h00;
    localparam logic [7:0] FAULT_CONCURRENT_CMD  = 8'h01;
    localparam logic [7:0] FAULT_CORE_BASE       = 8'h40;
    localparam logic [7:0] FAULT_ROUTE_BASE      = 8'h80;
    localparam logic [7:0] FAULT_COPY_PROTOCOL   = 8'hFE;

    typedef enum logic [4:0] {
        S_IDLE,
        S_RESET_ROUTE_START,
        S_RESET_ROUTE_WAIT,
        S_RESET_CORE_START,
        S_RESET_CORE_WAIT,
        S_RECURRENT_READ,
        S_RECURRENT_WAIT,
        S_RECURRENT_WRITE,
        S_CORE_TICK_START,
        S_CORE_TICK_WAIT,
        S_SPIKE_READ,
        S_SPIKE_WAIT,
        S_SPIKE_WRITE,
        S_ROUTE_START,
        S_ROUTE_WAIT
    } full_state_t;

    full_state_t state;

    logic [8:0]  latched_neuron_count;
    logic [10:0] latched_axon_count;
    logic [12:0] latched_synapse_count;
    logic [4:0]  latched_format_count;
    logic [12:0] latched_external_count;
    logic [12:0] latched_route_count;
    logic [12:0] latched_recurrent_count;
    logic        latched_recurrent_bank;
    logic [11:0] recurrent_copy_index;
    logic [15:0] recurrent_copy_data;
    logic [7:0]  spike_scan_index;
    logic        spike_scan_data;

    logic core_busy;
    logic core_reset_start_i;
    logic core_tick_start_i;
    logic core_reset_done_i;
    logic core_tick_done_i;
    logic [31:0] core_tick;
    logic core_fault;
    logic [7:0] core_fault_code;
    logic core_recurrent_we;
    logic core_debug_re;
    logic core_debug_rvalid;
    logic core_debug_spike;
    logic core_external_debug_rvalid;

    logic route_busy;
    logic route_reset_start_i;
    logic route_start_i;
    logic route_reset_done_i;
    logic route_done_i;
    logic route_fault;
    logic [7:0] route_fault_code;
    logic route_spike_we;
    logic route_debug_re_i;
    logic route_debug_bank_i;
    logic [11:0] route_debug_addr_i;
    logic route_debug_rvalid_i;
    logic [15:0] route_debug_rdata_i;

    assign busy = (state != S_IDLE);
    assign trace_external_event_count = latched_external_count;
    assign core_reset_start_i = (state == S_RESET_CORE_START);
    assign route_reset_start_i = (state == S_RESET_ROUTE_START);
    assign core_tick_start_i = (state == S_CORE_TICK_START);
    assign route_start_i = (state == S_ROUTE_START);

    assign core_recurrent_we = (state == S_RECURRENT_WRITE);
    assign core_debug_re = (state == S_SPIKE_READ)
        ? 1'b1
        : (debug_re && (state == S_IDLE));

    assign route_spike_we = (state == S_SPIKE_WRITE);
    assign route_debug_re_i = (state == S_RECURRENT_READ)
        ? 1'b1
        : (recurrent_debug_re && (state == S_IDLE));
    assign route_debug_bank_i = (state == S_RECURRENT_READ)
        ? latched_recurrent_bank
        : recurrent_debug_bank;
    assign route_debug_addr_i = (state == S_RECURRENT_READ)
        ? recurrent_copy_index
        : recurrent_debug_addr;

    assign debug_rvalid = (state == S_IDLE) ? core_debug_rvalid : 1'b0;
    assign debug_spike_rdata = core_debug_spike;
    assign external_debug_rvalid = (state == S_IDLE) ? core_external_debug_rvalid : 1'b0;
    assign recurrent_debug_rvalid = (state == S_IDLE) ? route_debug_rvalid_i : 1'b0;
    assign recurrent_debug_rdata = route_debug_rdata_i;

    integrated_core_controller_v1 #(
        .MAX_NEURONS(MAX_NEURONS),
        .MAX_AXONS(MAX_AXONS),
        .MAX_SYNAPSES(MAX_SYNAPSES),
        .MAX_FORMATS(MAX_FORMATS),
        .MAX_EVENTS(MAX_EVENTS)
    ) core_i (
        .ap_clk(ap_clk), .ap_rst(ap_rst),
        .core_reset_start(core_reset_start_i), .tick_start(core_tick_start_i),
        .neuron_count(latched_neuron_count), .axon_count(latched_axon_count),
        .synapse_count(latched_synapse_count), .format_count(latched_format_count),
        .external_event_count(latched_external_count),
        .recurrent_event_count(latched_recurrent_count),
        .busy(core_busy), .core_reset_done(core_reset_done_i), .tick_done(core_tick_done_i),
        .tick(core_tick), .fault(core_fault), .fault_code(core_fault_code),
        .active_neuron(active_neuron),
        .phase_b_active_source(), .phase_b_active_event_index(), .phase_b_active_synapse_index(),
        .trace_external_event_count(),
        .config_we(config_we && (state == S_IDLE)), .config_addr(config_addr), .config_wdata(config_wdata),
        .state_we(state_we && (state == S_IDLE)), .state_addr(state_addr), .state_wdata(state_wdata),
        .format_we(format_we && (state == S_IDLE)), .format_addr(format_addr), .format_wdata(format_wdata),
        .synapse_we(synapse_we && (state == S_IDLE)), .synapse_addr(synapse_addr), .synapse_wdata(synapse_wdata),
        .row_we(row_we && (state == S_IDLE)), .row_addr(row_addr), .row_wdata(row_wdata),
        .external_we(external_we && (state == S_IDLE)), .external_addr(external_addr), .external_wdata(external_wdata),
        .recurrent_we(core_recurrent_we), .recurrent_addr(recurrent_copy_index), .recurrent_wdata(recurrent_copy_data),
        .debug_re(core_debug_re),
        .debug_addr((state == S_SPIKE_READ || state == S_SPIKE_WAIT) ? spike_scan_index : debug_addr),
        .debug_rvalid(core_debug_rvalid),
        .debug_config_rdata(debug_config_rdata),
        .debug_state_before_rdata(debug_state_before_rdata),
        .debug_state_rdata(debug_state_rdata),
        .debug_synaptic_input_rdata(debug_synaptic_input_rdata),
        .debug_accum_rdata(debug_accum_rdata), .debug_spike_rdata(core_debug_spike),
        .debug_external_re(external_debug_re && (state == S_IDLE)),
        .debug_external_addr(external_debug_addr),
        .debug_external_rvalid(core_external_debug_rvalid),
        .debug_external_rdata(external_debug_rdata),
        .hls_ap_start(hls_ap_start), .hls_ap_done(hls_ap_done), .hls_ap_idle(hls_ap_idle), .hls_ap_ready(hls_ap_ready),
        .hls_current_before(hls_current_before), .hls_voltage_before(hls_voltage_before),
        .hls_refractory_before(hls_refractory_before), .hls_synaptic_input(hls_synaptic_input),
        .hls_current_decay(hls_current_decay), .hls_voltage_decay(hls_voltage_decay),
        .hls_threshold(hls_threshold), .hls_bias(hls_bias), .hls_reset_voltage(hls_reset_voltage),
        .hls_refractory_ticks(hls_refractory_ticks), .hls_current_after(hls_current_after),
        .hls_current_after_ap_vld(hls_current_after_ap_vld), .hls_voltage_after(hls_voltage_after),
        .hls_voltage_after_ap_vld(hls_voltage_after_ap_vld), .hls_refractory_after(hls_refractory_after),
        .hls_refractory_after_ap_vld(hls_refractory_after_ap_vld),
        .hls_spiked(hls_spiked), .hls_spiked_ap_vld(hls_spiked_ap_vld)
    );

    recurrent_route_queue_v1 #(
        .MAX_NEURONS(MAX_NEURONS), .MAX_AXONS(MAX_AXONS),
        .MAX_ROUTES(MAX_ROUTES), .MAX_EVENTS(MAX_EVENTS)
    ) route_i (
        .ap_clk(ap_clk), .ap_rst(ap_rst),
        .core_reset_start(route_reset_start_i), .start(route_start_i),
        .neuron_count(latched_neuron_count), .route_count(latched_route_count),
        .busy(route_busy), .core_reset_done(route_reset_done_i), .done(route_done_i),
        .fault(route_fault), .fault_code(route_fault_code),
        .current_bank(recurrent_current_bank), .current_count(recurrent_current_count),
        .last_consumed_count(last_consumed_recurrent_count), .last_routed_count(last_routed_count),
        .active_source(), .active_route_index(),
        .route_row_we(route_row_we && (state == S_IDLE)), .route_row_addr(route_row_addr), .route_row_wdata(route_row_wdata),
        .route_target_we(route_target_we && (state == S_IDLE)), .route_target_addr(route_target_addr), .route_target_wdata(route_target_wdata),
        .spike_we(route_spike_we), .spike_addr(spike_scan_index), .spike_wdata(spike_scan_data),
        .debug_re(route_debug_re_i), .debug_bank(route_debug_bank_i), .debug_addr(route_debug_addr_i),
        .debug_rvalid(route_debug_rvalid_i), .debug_rdata(route_debug_rdata_i),
        .debug_bank0_count(recurrent_bank0_count), .debug_bank1_count(recurrent_bank1_count)
    );

    always_ff @(posedge ap_clk) begin
        if (ap_rst) begin
            state                      <= S_IDLE;
            latched_neuron_count       <= 9'd0;
            latched_axon_count         <= 11'd0;
            latched_synapse_count      <= 13'd0;
            latched_format_count       <= 5'd0;
            latched_external_count     <= 13'd0;
            latched_route_count        <= 13'd0;
            latched_recurrent_count    <= 13'd0;
            latched_recurrent_bank     <= 1'b0;
            recurrent_copy_index       <= 12'd0;
            recurrent_copy_data        <= 16'd0;
            spike_scan_index           <= 8'd0;
            spike_scan_data            <= 1'b0;
            core_reset_done            <= 1'b0;
            tick_done                  <= 1'b0;
            tick                       <= 32'd0;
            fault                      <= 1'b0;
            fault_code                 <= FAULT_NONE;
        end else begin
            core_reset_done <= 1'b0;
            tick_done       <= 1'b0;

            case (state)
                S_IDLE: begin
                    if (core_reset_start && tick_start) begin
                        fault      <= 1'b1;
                        fault_code <= FAULT_CONCURRENT_CMD;
                    end else if (core_reset_start) begin
                        fault                    <= 1'b0;
                        fault_code               <= FAULT_NONE;
                        latched_neuron_count     <= neuron_count;
                        latched_axon_count       <= axon_count;
                        latched_synapse_count    <= synapse_count;
                        latched_format_count     <= format_count;
                        latched_external_count   <= 13'd0;
                        latched_recurrent_count  <= 13'd0;
                        latched_route_count      <= route_count;
                        state                    <= S_RESET_ROUTE_START;
                    end else if (tick_start) begin
                        fault                    <= 1'b0;
                        fault_code               <= FAULT_NONE;
                        latched_neuron_count     <= neuron_count;
                        latched_axon_count       <= axon_count;
                        latched_synapse_count    <= synapse_count;
                        latched_format_count     <= format_count;
                        latched_external_count   <= external_event_count;
                        latched_route_count      <= route_count;
                        latched_recurrent_count  <= recurrent_current_count;
                        latched_recurrent_bank   <= recurrent_current_bank;
                        recurrent_copy_index     <= 12'd0;
                        if (recurrent_current_count == 13'd0)
                            state <= S_CORE_TICK_START;
                        else
                            state <= S_RECURRENT_READ;
                    end
                end

                S_RESET_ROUTE_START: state <= S_RESET_ROUTE_WAIT;
                S_RESET_ROUTE_WAIT: begin
                    if (route_fault) begin
                        fault      <= 1'b1;
                        fault_code <= FAULT_ROUTE_BASE | route_fault_code;
                        state      <= S_IDLE;
                    end else if (route_reset_done_i) begin
                        state <= S_RESET_CORE_START;
                    end
                end

                S_RESET_CORE_START: state <= S_RESET_CORE_WAIT;
                S_RESET_CORE_WAIT: begin
                    if (core_fault) begin
                        fault      <= 1'b1;
                        fault_code <= FAULT_CORE_BASE | core_fault_code;
                        state      <= S_IDLE;
                    end else if (core_reset_done_i) begin
                        tick            <= 32'd0;
                        core_reset_done <= 1'b1;
                        state           <= S_IDLE;
                    end
                end

                S_RECURRENT_READ: state <= S_RECURRENT_WAIT;
                S_RECURRENT_WAIT: begin
                    if (!route_debug_rvalid_i) begin
                        fault      <= 1'b1;
                        fault_code <= FAULT_COPY_PROTOCOL;
                        state      <= S_IDLE;
                    end else begin
                        recurrent_copy_data <= route_debug_rdata_i;
                        state               <= S_RECURRENT_WRITE;
                    end
                end
                S_RECURRENT_WRITE: begin
                    if (({1'b0, recurrent_copy_index} + 13'd1) >= latched_recurrent_count) begin
                        state <= S_CORE_TICK_START;
                    end else begin
                        recurrent_copy_index <= recurrent_copy_index + 12'd1;
                        state                <= S_RECURRENT_READ;
                    end
                end

                S_CORE_TICK_START: state <= S_CORE_TICK_WAIT;
                S_CORE_TICK_WAIT: begin
                    if (core_fault) begin
                        fault      <= 1'b1;
                        fault_code <= FAULT_CORE_BASE | core_fault_code;
                        state      <= S_IDLE;
                    end else if (core_tick_done_i) begin
                        spike_scan_index <= 8'd0;
                        state            <= S_SPIKE_READ;
                    end
                end

                S_SPIKE_READ: state <= S_SPIKE_WAIT;
                S_SPIKE_WAIT: begin
                    if (!core_debug_rvalid) begin
                        fault      <= 1'b1;
                        fault_code <= FAULT_COPY_PROTOCOL;
                        state      <= S_IDLE;
                    end else begin
                        spike_scan_data <= core_debug_spike;
                        state           <= S_SPIKE_WRITE;
                    end
                end
                S_SPIKE_WRITE: begin
                    if (({1'b0, spike_scan_index} + 9'd1) >= latched_neuron_count) begin
                        state <= S_ROUTE_START;
                    end else begin
                        spike_scan_index <= spike_scan_index + 8'd1;
                        state            <= S_SPIKE_READ;
                    end
                end

                S_ROUTE_START: state <= S_ROUTE_WAIT;
                S_ROUTE_WAIT: begin
                    if (route_fault) begin
                        fault      <= 1'b1;
                        fault_code <= FAULT_ROUTE_BASE | route_fault_code;
                        state      <= S_IDLE;
                    end else if (route_done_i) begin
                        tick      <= core_tick;
                        tick_done <= 1'b1;
                        state     <= S_IDLE;
                    end
                end

                default: begin
                    fault      <= 1'b1;
                    fault_code <= 8'hFF;
                    state      <= S_IDLE;
                end
            endcase
        end
    end

endmodule
