#!/usr/bin/env python3
"""Generate Tcl data for P03 physical Python/FPGA conformance."""

from __future__ import annotations

import argparse
from pathlib import Path

from generate_p03_hls_vectors import _config
from loihi_twin_v2 import LogicalCore, SpikePacket
from loihi_twin_v2.hardware_p03 import (
    export_one_core_image,
    pack_compartment_state,
    pack_output_packet,
)

SCHEDULE = (
    (10,),
    (11,),
    (10, 12),
    (),
    (10,),
)


def _hex(value: int, bits: int) -> str:
    digits = (bits + 3) // 4
    mask = (1 << bits) - 1
    return f"0x{value & mask:0{digits}X}"


def _pair_list(entries: list[tuple[int, int]], bits: int) -> str:
    if not entries:
        return "[list]"
    body = " \\\n    ".join(f"[list {index} {_hex(word, bits)}]" for index, word in entries)
    return "[list \\\n    " + body + " \\\n]"


def _word_list(words: list[int], bits: int) -> str:
    if not words:
        return "[list]"
    return "[list " + " ".join(_hex(word, bits) for word in words) + "]"


def _int_list(values: tuple[int, ...] | list[int]) -> str:
    if not values:
        return "[list]"
    return "[list " + " ".join(str(value) for value in values) + "]"


def _trace_word(before: int, synaptic_input: int, after: int, spike: bool) -> int:
    return (
        (before & ((1 << 64) - 1))
        | ((synaptic_input & ((1 << 64) - 1)) << 64)
        | ((after & ((1 << 64) - 1)) << 128)
        | ((1 if spike else 0) << 192)
    )


def build_text() -> str:
    config = _config()
    image = export_one_core_image(config)
    core = LogicalCore(config)

    config_seeds = list(enumerate(image.config_words))
    state_seeds = list(enumerate(image.state_words))
    axon_seeds = [(seed.index, seed.word) for seed in image.axon_words]
    synapse_seeds = list(enumerate(image.synapse_words))
    route_desc_seeds = [
        (seed.index, seed.word) for seed in image.route_descriptor_words
    ]
    route_seeds = list(enumerate(image.route_words))

    lines = [
        "# Generated by examples/generate_p03_physical_vectors.py. Do not edit.",
        f"set P03_COMPARTMENT_COUNT {image.compartment_count}",
        f"set P03_SYNAPSE_COUNT {image.synapse_count}",
        f"set P03_ROUTE_COUNT {image.route_count}",
        f"set P03_CONFIG_SEEDS {_pair_list(config_seeds, 128)}",
        f"set P03_STATE_SEEDS {_pair_list(state_seeds, 64)}",
        f"set P03_AXON_SEEDS {_pair_list(axon_seeds, 64)}",
        f"set P03_SYNAPSE_SEEDS {_pair_list(synapse_seeds, 64)}",
        f"set P03_ROUTE_DESC_SEEDS {_pair_list(route_desc_seeds, 32)}",
        f"set P03_ROUTE_SEEDS {_pair_list(route_seeds, 32)}",
        "set P03_TICKS [list \\",
    ]

    for timestep, events in enumerate(SCHEDULE):
        for axon_id in events:
            core.ingest_packet(
                SpikePacket(
                    target_timestep=timestep,
                    destination_core=0,
                    destination_axon=axon_id,
                )
            )
        trace = core.evaluate(timestep)
        synaptic_input = [0] * image.compartment_count
        for contribution in trace.synaptic_contributions:
            synaptic_input[contribution.target_compartment] += contribution.weight
        spike_set = set(trace.spikes_out)

        expected_states: list[int] = []
        expected_traces: list[int] = []
        for compartment_id in range(image.compartment_count):
            before = pack_compartment_state(
                trace.compartment_state_before[compartment_id].state
            )
            after = pack_compartment_state(
                trace.compartment_state_after[compartment_id].state
            )
            expected_states.append(after)
            expected_traces.append(
                _trace_word(
                    before,
                    synaptic_input[compartment_id],
                    after,
                    compartment_id in spike_set,
                )
            )

        packets = [pack_output_packet(packet) for packet in trace.packets_out]
        lines.append(
            "    [dict create "
            f"timestep {timestep} "
            f"events {_int_list(list(events))} "
            f"spike_count {len(spike_set)} "
            f"states {_word_list(expected_states, 64)} "
            f"traces {_word_list(expected_traces, 256)} "
            f"packets {_word_list(packets, 64)}] \\")

    lines.extend([
        "]",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_text(), encoding="utf-8")
    print(
        f"P03 generated physical corpus: output={args.output} "
        f"ticks={len(SCHEDULE)} compartments=3"
    )


if __name__ == "__main__":
    main()
