#!/usr/bin/env python3
"""Emit deterministic Tcl host-load vectors from one P06 compiled deployment."""

from __future__ import annotations

import argparse
from pathlib import Path

from loihi_twin_v2 import CompiledDeployment, export_compiled_fpga_image


def _hex(value: int, bits: int) -> str:
    digits = (bits + 3) // 4
    mask = (1 << bits) - 1
    return f"0x{value & mask:0{digits}X}"


def _pair_list(entries: list[tuple[int, int]], bits: int) -> str:
    return "{" + " ".join(
        "{" + f"{index} {_hex(word, bits)}" + "}" for index, word in entries
    ) + "}"


def _context_dict(context) -> str:
    image = context.image
    config = list(enumerate(image.config_words))
    state = list(enumerate(image.state_words))
    axons = [(seed.index, seed.word) for seed in image.axon_words]
    synapses = list(enumerate(image.synapse_words))
    route_desc = [(seed.index, seed.word) for seed in image.route_descriptor_words]
    routes = list(enumerate(image.route_words))
    return (
        "{"
        f"slot {context.context_slot} "
        f"logical_core_id {context.logical_core_id} "
        f"metadata {_hex(context.metadata_word(), 64)} "
        f"compartment_count {image.compartment_count} "
        f"synapse_count {image.synapse_count} "
        f"route_count {image.route_count} "
        f"config_seeds {_pair_list(config, 128)} "
        f"state_seeds {_pair_list(state, 64)} "
        f"axon_seeds {_pair_list(axons, 64)} "
        f"synapse_seeds {_pair_list(synapses, 64)} "
        f"route_desc_seeds {_pair_list(route_desc, 32)} "
        f"route_seeds {_pair_list(routes, 32)}"
        "}"
    )


def build_text(compiled: CompiledDeployment) -> str:
    fpga = export_compiled_fpga_image(compiled)
    lines = [
        "# Generated by examples/generate_p06_fpga_load_vectors.py. Do not edit.",
        f"set P06_DEPLOYMENT_SCHEMA {compiled.to_dict()['schema']}",
        f"set P06_COMPILER_VERSION {compiled.compiler_version}",
        f"set P06_SOURCE_FINGERPRINT {compiled.source_fingerprint}",
        f"set P06_DEPLOYMENT_FINGERPRINT {compiled.fingerprint}",
        f"set P06_LOGICAL_CORES {fpga.logical_core_count}",
        f"set P06_PHYSICAL_ENGINES {fpga.hardware_image.physical_engine_count}",
        "set P06_CONTEXTS {",
    ]
    for context in fpga.hardware_image.contexts:
        lines.append(f"    {_context_dict(context)}")
    lines.append("}")
    lines.append("set P06_INGRESS_ROUTES {")
    for route in sorted(compiled.ingress_routes):
        lines.append(
            "    {"
            f"input_population {route.input_population} "
            f"input_index {route.input_index} "
            f"destination_core {route.destination_core} "
            f"destination_axon {route.destination_axon}"
            "}"
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("deployment", type=Path, help="P06 compiled deployment JSON")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    compiled = CompiledDeployment.read_json(args.deployment)
    text = build_text(compiled)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(
        "P06 FPGA load-vector generation PASS: "
        f"deployment={compiled.fingerprint} output={args.output}"
    )


if __name__ == "__main__":
    main()
