#!/usr/bin/env python3
"""Generate physical expectations for the P07 six-layer compiled SNN.

The accepted P06 Hardware Manager harness is intentionally reused, so this file
emits the P06_* Tcl variable contract plus P07 workload metadata.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from loihi_twin_v2 import CompiledDeployment, export_compiled_fpga_image
from loihi_twin_v2.hardware_p03 import pack_compartment_state, pack_output_packet


def _hex(value: int, bits: int) -> str:
    digits = (bits + 3) // 4
    return f"0x{value & ((1 << bits) - 1):0{digits}X}"


def _pair_list(entries: list[tuple[int, int]], bits: int) -> str:
    return "{" + " ".join(
        "{" + f"{index} {_hex(word, bits)}" + "}" for index, word in entries
    ) + "}"


def _word_list(words: list[int], bits: int) -> str:
    return "{" + " ".join(_hex(word, bits) for word in words) + "}"


def _int_list(values: list[int] | tuple[int, ...]) -> str:
    return "{" + " ".join(str(value) for value in values) + "}"


def _trace_word(before: int, synaptic_input: int, after: int, spike: bool) -> int:
    return (
        (before & ((1 << 64) - 1))
        | ((synaptic_input & ((1 << 64) - 1)) << 64)
        | ((after & ((1 << 64) - 1)) << 128)
        | ((1 if spike else 0) << 192)
    )


def _context_dict(context) -> str:
    image = context.image
    return (
        "{"
        f"slot {context.context_slot} "
        f"logical_core_id {context.logical_core_id} "
        f"compartment_count {image.compartment_count} "
        f"synapse_count {image.synapse_count} "
        f"route_count {image.route_count} "
        f"config_seeds {_pair_list(list(enumerate(image.config_words)), 128)} "
        f"state_seeds {_pair_list(list(enumerate(image.state_words)), 64)} "
        f"axon_seeds {_pair_list([(seed.index, seed.word) for seed in image.axon_words], 64)} "
        f"synapse_seeds {_pair_list(list(enumerate(image.synapse_words)), 64)} "
        f"route_desc_seeds {_pair_list([(seed.index, seed.word) for seed in image.route_descriptor_words], 32)} "
        f"route_seeds {_pair_list(list(enumerate(image.route_words)), 32)}"
        "}"
    )


def build_text(compiled: CompiledDeployment) -> str:
    fpga = export_compiled_fpga_image(compiled)
    if fpga.logical_core_count != 3:
        raise ValueError("P07 physical corpus requires exactly three compiled logical cores")
    if any(context.image.compartment_count != 4 for context in fpga.hardware_image.contexts):
        raise ValueError("P07 physical corpus requires four occupied compartments per context")

    slot_for_core = fpga.logical_to_context_slot
    contexts = fpga.hardware_image.contexts
    scenarios = (
        ("pixel0", (0,)),
        ("pixel0_pixel2", (0, 2)),
        ("all_pixels", (0, 1, 2, 3)),
    )
    lines = [
        "# Generated by examples/generate_p07_physical_vectors.py. Do not edit.",
        f"set P06_SOURCE_FINGERPRINT {compiled.source_fingerprint}",
        f"set P06_DEPLOYMENT_FINGERPRINT {compiled.fingerprint}",
        "set P06_LOGICAL_CONTEXTS 3",
        "set P06_PHYSICAL_ENGINES 1",
        "set P07_LAYERS 6",
        "set P07_NEURONS 12",
        "set P07_INPUT_CHANNELS 4",
        "set P06_SCENARIOS {",
    ]

    for name, active_inputs in scenarios:
        chip = compiled.build_chip()
        initial_packets = compiled.external_packets("pixels", active_inputs, target_timestep=0)
        initial_events = [[], [], []]
        for packet in initial_packets:
            initial_events[slot_for_core[packet.destination_core]].append(packet.destination_axon)

        metadata = 0
        for context in contexts:
            slot = context.context_slot
            metadata |= context.metadata_word(len(initial_events[slot])) << (64 * slot)

        tick_lines: list[str] = []
        for timestep in range(7):
            trace = chip.step(initial_packets if timestep == 0 else ())
            expected_contexts: list[str] = []
            next_events = [[], [], []]
            local_packets = 0
            remote_packets = 0

            for context in contexts:
                logical_id = context.logical_core_id
                core_trace = next(core for core in trace.cores if core.logical_core_id == logical_id)
                synaptic_input = [0] * len(core_trace.compartment_state_after)
                for contribution in core_trace.synaptic_contributions:
                    synaptic_input[contribution.target_compartment] += contribution.weight
                spike_set = set(core_trace.spikes_out)
                states: list[int] = []
                traces: list[int] = []
                for compartment_id in range(len(core_trace.compartment_state_after)):
                    before = pack_compartment_state(
                        core_trace.compartment_state_before[compartment_id].state
                    )
                    after = pack_compartment_state(
                        core_trace.compartment_state_after[compartment_id].state
                    )
                    states.append(after)
                    traces.append(
                        _trace_word(
                            before,
                            synaptic_input[compartment_id],
                            after,
                            compartment_id in spike_set,
                        )
                    )

                packet_words = [pack_output_packet(packet) for packet in core_trace.packets_out]
                for packet in core_trace.packets_out:
                    destination_slot = slot_for_core[packet.destination_core]
                    next_events[destination_slot].append(packet.destination_axon)
                    if packet.destination_core == packet.source_core:
                        local_packets += 1
                    else:
                        remote_packets += 1

                expected_contexts.append(
                    "{"
                    f"slot {context.context_slot} "
                    f"logical_core_id {logical_id} "
                    f"spike_count {len(spike_set)} "
                    f"packet_count {len(packet_words)} "
                    f"states {_word_list(states, 64)} "
                    f"traces {_word_list(traces, 256)} "
                    f"packets {_word_list(packet_words, 64)}"
                    "}"
                )

            tick_lines.append(
                "{"
                f"timestep {timestep} "
                "contexts {" + " ".join(expected_contexts) + "} "
                f"next_events0 {_int_list(next_events[0])} "
                f"next_events1 {_int_list(next_events[1])} "
                f"next_events2 {_int_list(next_events[2])} "
                f"local_packets {local_packets} "
                f"remote_packets {remote_packets}"
                "}"
            )

        lines.append(
            "    {"
            f"name {name} "
            f"context_metadata {_hex(metadata, 192)} "
            "contexts {" + " ".join(_context_dict(context) for context in contexts) + "} "
            f"initial_events0 {_int_list(initial_events[0])} "
            f"initial_events1 {_int_list(initial_events[1])} "
            f"initial_events2 {_int_list(initial_events[2])} "
            "ticks {" + " ".join(tick_lines) + "}"
            "}"
        )

    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("deployment", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    compiled = CompiledDeployment.read_json(args.deployment)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_text(compiled), encoding="utf-8")
    print(
        "P07 physical corpus generation PASS: "
        f"deployment={compiled.fingerprint} layers=6 scenarios=3 ticks_per_order=7 output={args.output}"
    )


if __name__ == "__main__":
    main()
