"""Loihi-1 architectural digital-twin v2 golden model."""

from .arithmetic import ArithmeticConfig, OverflowMode, round_away_from_zero
from .axon import InputAxonBinding, OutputRoute, OutputRouteEntry
from .chip import LogicalChip
from .compartment import CompartmentConfig, CompartmentState, step_compartment
from .compiler import (
    CompiledDeployment,
    IngressRoute,
    InputPopulationSpec,
    InputProjectionSpec,
    MappingError,
    MappingOptions,
    NetworkSpec,
    P06_COMPILER_VERSION,
    P06_DEPLOYMENT_SCHEMA,
    P06_NETWORK_SCHEMA,
    PlacementRecord,
    PopulationSpec,
    ProjectionConnection,
    ProjectionSpec,
    compile_network,
)
from .core import LogicalCore, LogicalCoreConfig
from .hardware_p03 import (
    OneCoreHardwareImage,
    P03_PROFILE_NAME,
    P03_REQUIRED_ARITHMETIC,
    SparseWord,
    export_one_core_image,
    pack_compartment_config,
    pack_compartment_state,
    pack_output_packet,
    unpack_compartment_config,
    unpack_compartment_state,
    unpack_output_packet,
)
from .hardware_p04 import (
    P04_PHYSICAL_COMPARTMENTS,
    P04_PHYSICAL_INPUT_AXONS,
    P04_PHYSICAL_INPUT_EVENTS,
    P04_PHYSICAL_OUTPUT_PACKETS,
    P04_PHYSICAL_OUTPUT_ROUTES,
    P04_PHYSICAL_SYNAPSE_ENTRIES,
    P04_PROFILE_NAME,
    TwoCoreValidationImage,
    export_two_core_validation_image,
)
from .hardware_p05 import (
    LogicalContextImage,
    P05_CONTEXT_BITS_PER_CORE,
    P05_ESTIMATED_URAM288,
    P05_K26_URAM288_AVAILABLE,
    P05_MAX_RESIDENT_CONTEXTS,
    P05_PHYSICAL_ENGINE_COUNT,
    P05_PROFILE_NAME,
    VirtualizedHardwareImage,
    export_virtualized_hardware_image,
)
from .hardware_p06 import (
    P06_FPGA_PROFILE_NAME,
    CompiledFpgaImage,
    export_compiled_fpga_image,
)
from .hardware_p08 import (
    BackingLogicalContextImage,
    P08_PAGED_FPGA_PROFILE_NAME,
    P08_RESIDENT_CONTEXT_COUNT,
    PagedCompiledFpgaImage,
    PagedHardwareImage,
    ResidentPageImage,
    export_paged_compiled_fpga_image,
    export_paged_hardware_image,
)
from .mapping import Deployment
from .packet import PacketClass, RouteScope, SpikePacket
from .paging import (
    ContextPageDispatch,
    ContextPagingReport,
    ContextPagingSchedule,
    DeterministicContextPager,
    P08_PAGING_POLICY,
    P08_ROUTE_DELIVERY_POLICY,
    PagedVirtualizedLogicalChip,
)
from .reporting import deployment_report, trace_report
from .resources import (
    MAX_COMPARTMENTS_PER_CORE,
    MAX_INPUT_AXONS_PER_CORE,
    MAX_LOGICAL_CORES,
    MAX_OUTPUT_ROUTES_PER_CORE,
    MAX_SYNAPSE_MEMORY_BYTES_PER_CORE,
    CoreCapacity,
    ResourceCapacityError,
    ResourceUsage,
    SynapseCostModel,
)
from .runtime import RunResult, run_deployment
from .synapse import SynapseEntry, SynapseTemplate
from .virtualization import (
    DeterministicCoreScheduler,
    VirtualDispatch,
    VirtualizationReport,
    VirtualizationSchedule,
    VirtualizedLogicalChip,
)

__all__ = [
    "ArithmeticConfig",
    "OverflowMode",
    "round_away_from_zero",
    "InputAxonBinding",
    "OutputRoute",
    "OutputRouteEntry",
    "LogicalChip",
    "CompartmentConfig",
    "CompartmentState",
    "step_compartment",
    "LogicalCore",
    "LogicalCoreConfig",
    "Deployment",
    "PopulationSpec",
    "InputPopulationSpec",
    "ProjectionConnection",
    "ProjectionSpec",
    "InputProjectionSpec",
    "NetworkSpec",
    "MappingOptions",
    "MappingError",
    "PlacementRecord",
    "IngressRoute",
    "CompiledDeployment",
    "compile_network",
    "P06_NETWORK_SCHEMA",
    "P06_DEPLOYMENT_SCHEMA",
    "P06_COMPILER_VERSION",
    "PacketClass",
    "RouteScope",
    "SpikePacket",
    "deployment_report",
    "trace_report",
    "RunResult",
    "run_deployment",
    "CoreCapacity",
    "ResourceCapacityError",
    "ResourceUsage",
    "SynapseCostModel",
    "SynapseEntry",
    "SynapseTemplate",
    "OneCoreHardwareImage",
    "SparseWord",
    "P03_PROFILE_NAME",
    "P03_REQUIRED_ARITHMETIC",
    "export_one_core_image",
    "pack_compartment_config",
    "unpack_compartment_config",
    "pack_compartment_state",
    "unpack_compartment_state",
    "pack_output_packet",
    "unpack_output_packet",
    "P04_PROFILE_NAME",
    "TwoCoreValidationImage",
    "export_two_core_validation_image",
    "P04_PHYSICAL_COMPARTMENTS",
    "P04_PHYSICAL_INPUT_AXONS",
    "P04_PHYSICAL_SYNAPSE_ENTRIES",
    "P04_PHYSICAL_OUTPUT_ROUTES",
    "P04_PHYSICAL_INPUT_EVENTS",
    "P04_PHYSICAL_OUTPUT_PACKETS",
    "P05_PROFILE_NAME",
    "P05_PHYSICAL_ENGINE_COUNT",
    "P05_MAX_RESIDENT_CONTEXTS",
    "P05_CONTEXT_BITS_PER_CORE",
    "P05_ESTIMATED_URAM288",
    "P05_K26_URAM288_AVAILABLE",
    "LogicalContextImage",
    "VirtualizedHardwareImage",
    "export_virtualized_hardware_image",
    "P06_FPGA_PROFILE_NAME",
    "CompiledFpgaImage",
    "export_compiled_fpga_image",
    "P08_PAGED_FPGA_PROFILE_NAME",
    "P08_RESIDENT_CONTEXT_COUNT",
    "BackingLogicalContextImage",
    "ResidentPageImage",
    "PagedHardwareImage",
    "PagedCompiledFpgaImage",
    "export_paged_hardware_image",
    "export_paged_compiled_fpga_image",
    "P08_PAGING_POLICY",
    "P08_ROUTE_DELIVERY_POLICY",
    "ContextPageDispatch",
    "ContextPagingSchedule",
    "ContextPagingReport",
    "DeterministicContextPager",
    "PagedVirtualizedLogicalChip",
    "DeterministicCoreScheduler",
    "VirtualDispatch",
    "VirtualizationReport",
    "VirtualizationSchedule",
    "VirtualizedLogicalChip",
    "MAX_LOGICAL_CORES",
    "MAX_COMPARTMENTS_PER_CORE",
    "MAX_INPUT_AXONS_PER_CORE",
    "MAX_OUTPUT_ROUTES_PER_CORE",
    "MAX_SYNAPSE_MEMORY_BYTES_PER_CORE",
]
