from __future__ import annotations

import argparse
from pathlib import Path

from neuromorphic_twin.fpga_single_tick_conformance import (
    build_m12_single_tick_cases,
    write_m12_single_tick_corpus,
)


def _hex(value: int, width: int) -> str:
    return f"{value & ((1 << width) - 1):0{(width + 3) // 4}x}"


def _pad(values: tuple[int, ...], count: int) -> tuple[int, ...]:
    if len(values) > count:
        raise ValueError("generated M12.2 row exceeds frozen include stride")
    return values + (0,) * (count - len(values))


def write_systemverilog_include(output: Path) -> Path:
    """Write only FPGA load inputs; Python-golden outputs stay host-side."""

    cases = build_m12_single_tick_cases()
    max_neurons = max(case.neuron_count for case in cases)
    max_axons = max(case.storage.axon_count for case in cases)
    max_synapses = max(case.storage.synapse_count for case in cases)
    max_formats = max(case.storage.format_count for case in cases)
    max_routes = max(case.routes.route_count for case in cases)
    max_external = max(len(case.external_axons) for case in cases)

    lines = [
        "// Generated by examples/generate_m12_2_single_tick_corpus.py; do not edit.",
        "// IMPORTANT: this include contains only case inputs/load images. Python-golden",
        "// expected outputs are deliberately kept out of FPGA-visible source.",
        f"localparam int M12_2_CASE_COUNT = {len(cases)};",
        f"localparam int M12_2_MAX_NEURONS = {max_neurons};",
        f"localparam int M12_2_MAX_AXONS = {max_axons};",
        f"localparam int M12_2_MAX_SYNAPSES = {max_synapses};",
        f"localparam int M12_2_MAX_FORMATS = {max_formats};",
        f"localparam int M12_2_MAX_ROUTES = {max_routes};",
        f"localparam int M12_2_MAX_EXTERNAL_EVENTS = {max_external};",
        "",
    ]

    def emit(name: str, width: int, words: tuple[int, ...]) -> None:
        lines.append(
            f"localparam logic [{width - 1}:0] {name} [0:{len(words) - 1}] = '{{"
        )
        for index, word in enumerate(words):
            comma = "," if index + 1 != len(words) else ""
            lines.append(f"    {width}'h{_hex(word, width)}{comma}")
        lines.append("};")
        lines.append("")

    emit("M12_2_NEURON_COUNTS", 9, tuple(case.neuron_count for case in cases))
    emit("M12_2_AXON_COUNTS", 11, tuple(case.storage.axon_count for case in cases))
    emit("M12_2_SYNAPSE_COUNTS", 13, tuple(case.storage.synapse_count for case in cases))
    emit("M12_2_FORMAT_COUNTS", 5, tuple(case.storage.format_count for case in cases))
    emit("M12_2_ROUTE_COUNTS", 13, tuple(case.routes.route_count for case in cases))
    emit("M12_2_EXTERNAL_COUNTS", 13, tuple(len(case.external_axons) for case in cases))

    emit(
        "M12_2_CONFIG_WORDS",
        128,
        tuple(
            word
            for case in cases
            for word in _pad(case.config_words, max_neurons)
        ),
    )
    emit(
        "M12_2_INITIAL_STATE_WORDS",
        64,
        tuple(
            word
            for case in cases
            for word in _pad(case.initial_state_words, max_neurons)
        ),
    )
    emit(
        "M12_2_FORMAT_WORDS",
        16,
        tuple(
            word
            for case in cases
            for word in _pad(case.storage.format_words, max_formats)
        ),
    )
    emit(
        "M12_2_SYNAPSE_WORDS",
        32,
        tuple(
            word
            for case in cases
            for word in _pad(case.storage.synapse_words, max_synapses)
        ),
    )
    emit(
        "M12_2_WEIGHT_ROWS",
        32,
        tuple(
            word
            for case in cases
            for word in _pad(case.storage.axon_row_pointers, max_axons + 1)
        ),
    )
    emit(
        "M12_2_ROUTE_ROWS",
        32,
        tuple(
            word
            for case in cases
            for word in _pad(case.routes.row_pointers, max_neurons + 1)
        ),
    )
    emit(
        "M12_2_ROUTE_TARGETS",
        16,
        tuple(
            word
            for case in cases
            for word in _pad(case.routes.target_axons, max_routes)
        ),
    )
    emit(
        "M12_2_EXTERNAL_EVENTS",
        16,
        tuple(
            word
            for case in cases
            for word in _pad(case.external_axons, max_external)
        ),
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the M12.2 directed one-tick FPGA load corpus and Python golden artifacts."
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--sv-output", type=Path, required=True)
    args = parser.parse_args()

    manifest = write_m12_single_tick_corpus(args.output_dir)
    include = write_systemverilog_include(args.sv_output)
    cases = build_m12_single_tick_cases()
    print(
        "M12.2 directed single-tick corpus generated: "
        f"cases={len(cases)} manifest={manifest} sv={include}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
