from __future__ import annotations

import argparse
from pathlib import Path

from generate_m11_5_4_integrated_vectors import (
    M11_5_4I_NEURON_COUNT,
    M11_5_4I_TICK_COUNT,
    integrated_vectors,
)

M11_5_5_TRACE_TAG = 0x4D353554  # "M55T"


def _hex(value: int, width: int) -> str:
    return f"{value & ((1 << width) - 1):0{(width + 3) // 4}x}"


def trace_state_before_words() -> tuple[int, ...]:
    values = integrated_vectors()
    initial = tuple(int(value) for value in values["initial_state_words"])
    states = tuple(tuple(int(word) for word in row) for row in values["expected_states"])

    before_by_tick: list[tuple[int, ...]] = []
    for tick_index in range(M11_5_4I_TICK_COUNT):
        before_by_tick.append(initial if tick_index == 0 else states[tick_index - 1])

    return tuple(word for row in before_by_tick for word in row)


def write_systemverilog_include(output: Path) -> Path:
    words = trace_state_before_words()
    expected_words = M11_5_4I_TICK_COUNT * M11_5_4I_NEURON_COUNT
    assert len(words) == expected_words

    lines = [
        "// Generated by examples/generate_m11_5_5_trace_vectors.py; do not edit.",
        f"localparam logic [31:0] M11_5_5_TRACE_TAG = 32'h{M11_5_5_TRACE_TAG:08x};",
        (
            "localparam logic [63:0] M11_5_5_EXPECTED_STATE_BEFORE "
            f"[0:{expected_words - 1}] = '{{"
        ),
    ]
    for index, word in enumerate(words):
        comma = "," if index + 1 != len(words) else ""
        lines.append(f"    64'h{_hex(word, 64)}{comma}")
    lines.extend(["};", ""])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    output = write_systemverilog_include(args.output)
    print(
        "M11.5.5 trace snapshot vectors generated: "
        f"ticks={M11_5_4I_TICK_COUNT}, neurons={M11_5_4I_NEURON_COUNT}, "
        f"tag=0x{M11_5_5_TRACE_TAG:08X}"
    )
    print(f"output={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
