from __future__ import annotations

import argparse
from pathlib import Path

from neuromorphic_twin.fpga_multitick_conformance import (
    build_m12_multitick_cases,
    write_m12_multitick_corpus,
)


def _hex(value: int, width: int) -> str:
    return f"{value & ((1 << width) - 1):0{(width + 3) // 4}x}"


def _pad(values: tuple[int, ...], count: int) -> tuple[int, ...]:
    if len(values) > count:
        raise ValueError("generated M12.3 row exceeds frozen include stride")
    return values + (0,) * (count - len(values))


def write_systemverilog_include(output: Path) -> Path:
    """Write only physical inputs; recurrent events and golden outputs stay absent."""

    cases = build_m12_multitick_cases()
    max_neurons = max(case.neuron_count for case in cases)
    max_axons = max(case.storage.axon_count for case in cases)
    max_synapses = max(case.storage.synapse_count for case in cases)
    max_formats = max(case.storage.format_count for case in cases)
    max_routes = max(case.routes.route_count for case in cases)
    max_ticks = max(case.tick_count for case in cases)
    max_external = max(len(events) for case in cases for events in case.external_schedule)

    lines = [
        "// Generated by examples/generate_m12_3_multitick_corpus.py; do not edit.",
        "// INPUTS ONLY: no Python-golden state/spike/queue outputs and no recurrent-event",
        "// schedule are present. Recurrence must be generated by the FPGA itself.",
        f"localparam int M12_3_CASE_COUNT = {len(cases)};",
        f"localparam int M12_3_MAX_NEURONS = {max_neurons};",
        f"localparam int M12_3_MAX_AXONS = {max_axons};",
        f"localparam int M12_3_MAX_SYNAPSES = {max_synapses};",
        f"localparam int M12_3_MAX_FORMATS = {max_formats};",
        f"localparam int M12_3_MAX_ROUTES = {max_routes};",
        f"localparam int M12_3_MAX_TICKS = {max_ticks};",
        f"localparam int M12_3_MAX_EXTERNAL_EVENTS = {max_external};",
        "",
    ]

    def emit(name: str, width: int, words: tuple[int, ...]) -> None:
        lines.append(
            f"localparam logic [{width - 1}:0] {name} [0:{len(words) - 1}] = '{{"
        )
        for index, word in enumerate(words):
            comma = "," if index + 1 != len(words) else ""
            lines.append(f"    {width}'h{_hex(word, width)}{comma}")
        lines.append("};")
        lines.append("")

    emit("M12_3_NEURON_COUNTS", 9, tuple(case.neuron_count for case in cases))
    emit("M12_3_AXON_COUNTS", 11, tuple(case.storage.axon_count for case in cases))
    emit("M12_3_SYNAPSE_COUNTS", 13, tuple(case.storage.synapse_count for case in cases))
    emit("M12_3_FORMAT_COUNTS", 5, tuple(case.storage.format_count for case in cases))
    emit("M12_3_ROUTE_COUNTS", 13, tuple(case.routes.route_count for case in cases))
    emit("M12_3_TICK_COUNTS", 8, tuple(case.tick_count for case in cases))

    emit(
        "M12_3_CONFIG_WORDS",
        128,
        tuple(word for case in cases for word in _pad(case.config_words, max_neurons)),
    )
    emit(
        "M12_3_INITIAL_STATE_WORDS",
        64,
        tuple(word for case in cases for word in _pad(case.initial_state_words, max_neurons)),
    )
    emit(
        "M12_3_FORMAT_WORDS",
        16,
        tuple(word for case in cases for word in _pad(case.storage.format_words, max_formats)),
    )
    emit(
        "M12_3_SYNAPSE_WORDS",
        32,
        tuple(word for case in cases for word in _pad(case.storage.synapse_words, max_synapses)),
    )
    emit(
        "M12_3_WEIGHT_ROWS",
        32,
        tuple(
            word
            for case in cases
            for word in _pad(case.storage.axon_row_pointers, max_axons + 1)
        ),
    )
    emit(
        "M12_3_ROUTE_ROWS",
        32,
        tuple(
            word
            for case in cases
            for word in _pad(case.routes.row_pointers, max_neurons + 1)
        ),
    )
    emit(
        "M12_3_ROUTE_TARGETS",
        16,
        tuple(
            word
            for case in cases
            for word in _pad(case.routes.target_axons, max_routes)
        ),
    )

    external_counts: list[int] = []
    external_words: list[int] = []
    for case in cases:
        padded_ticks = case.external_schedule + ((),) * (max_ticks - case.tick_count)
        for events in padded_ticks:
            external_counts.append(len(events))
            external_words.extend(_pad(tuple(events), max_external))
    emit("M12_3_EXTERNAL_COUNTS", 13, tuple(external_counts))
    emit("M12_3_EXTERNAL_EVENTS", 16, tuple(external_words))

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def write_hardware_case_metadata(output: Path) -> Path:
    cases = build_m12_multitick_cases()
    lines = ["case_id\tcase_name\tneuron_count\ttick_count"]
    lines.extend(
        f"{case.case_id}\t{case.name}\t{case.neuron_count}\t{case.tick_count}"
        for case in cases
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate M12.3 directed multi-tick FPGA inputs and Python golden timelines."
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--sv-output", type=Path, required=True)
    args = parser.parse_args()

    manifest = write_m12_multitick_corpus(args.output_dir)
    include = write_systemverilog_include(args.sv_output)
    metadata = write_hardware_case_metadata(args.output_dir / "hardware_cases.tsv")
    cases = build_m12_multitick_cases()
    print(
        "M12.3 directed multi-tick corpus generated: "
        f"cases={len(cases)} ticks={sum(case.tick_count for case in cases)} "
        f"manifest={manifest} metadata={metadata} sv={include}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
