from pathlib import Path

root = Path(__file__).resolve().parents[1]
path = root / "MILESTONES.md"
text = path.read_text(encoding="utf-8")

text = text.replace(
    "| M12 | Validate FPGA against Python golden model | In progress | 2026-08-27 | — |",
    "| M12 | Validate FPGA against Python golden model | In progress | 2026-08-27 | — |",
)
text = text.replace(
    "- [ ] Directed multi-tick and recurrent physical scenarios match Python exactly at every compared tick.",
    "- [x] Directed multi-tick and recurrent physical scenarios match Python exactly at every compared tick.",
)

start = text.index("### M12.3 — Multi-tick and recurrent-network physical conformance")
end = text.index("\n---\n\n### M12.4 — Broad deterministic physical regression and boundary stress", start)
replacement = '''### M12.3 — Multi-tick and recurrent-network physical conformance

**Status:** Complete  
**Started:** 2026-09-07  
**Completed:** 2026-09-07  
**Repository evidence:** branch `agent/m12-3-multitick-recurrent-physical`; physical KV260 closure with 10 directed scenarios / 40 committed ticks plus independent six-tick reset/replay

#### Core goal

Prove that Python/FPGA equivalence survives state history, recurrent queue swaps, event ordering, fan-in/fan-out, and repeated algorithmic ticks rather than matching only isolated transitions.

#### Delivered

- Added a Python-authoritative directed corpus of 10 multi-tick workloads totaling 40 committed ticks. Coverage includes a feed-forward recurrent chain, self-recurrence, a two-neuron recurrent loop, recurrent fan-out, recurrent fan-in, same-target multiplicity, external-plus-recurrent coincidence, simultaneous deterministic routing order, quiescence followed by renewed input, and multi-tick decay/refractory history.
- The FPGA-visible generated SystemVerilog contains only static load images and the per-tick external-event schedule. It contains no Python-golden state/spike/queue outputs and no recurrent-event schedule; recurrent inputs must be generated by the FPGA's own prior-tick routing and double-buffered queue state.
- Added a case-selectable host-stepped M12.3 capture shell around the unchanged M11.5 recurrent integrated core and the corrected M12 trace bridge. Every committed tick pauses in an immutable trace window before the host loads the next tick's external events.
- Added exact per-tick host-side comparison for state-before/state-after words, signed-64 synaptic sums, spikes, external input events, consumed recurrent events, newly routed recurrent events, active recurrent bank/counts, architectural tick, and fault state.
- Added a source-controlled Vivado 2025.2 K26 build flow plus a Hardware Manager capture flow that programs the bitstream once and executes all 10 directed scenarios / 40 committed ticks.
- Added a separate reset/replay closure session for case 02 (`two-neuron-recurrent-loop`). The board is independently programmed/reset, the six-tick workload is captured again, both captures must independently match Python, and their typed physical traces must match each other exactly.
- Preserved the M12.2 synchronous recurrent-bank debug-selector correction and regression while reusing that validated physical observation path for repeated bank swaps.

#### Final physical completion evidence

The complete KV260 M12.3 hardware suite finished successfully on 2026-09-07. The directed suite captured all 10 scenarios and 40 committed ticks, and the host-side exact differential completed with zero mismatches:

```text
M12.3 physical directed multi-tick suite capture completed successfully: cases=10 ticks=40
M12.3 exact physical multi-tick differential passed: cases=10 ticks=40 mismatches=0
```

The independent reset/replay session then reran the six-tick recurrent-loop anchor. Every replay tick matched Python exactly, the typed physical trace matched the first capture, and the serialized JSON artifacts were byte-identical:

```text
M12.3 targeted case PASS: 02 two-neuron-recurrent-loop ticks=6 mismatches=0
M12.3 reset/replay passed: case=02 name=two-neuron-recurrent-loop ticks=6 semantic_exact=1 first_sha256=1d261d6d4a52e37a95a3dfdd3b6f0e76fdfb21e87b1404bc81cbc41f646c78a3 replay_sha256=1d261d6d4a52e37a95a3dfdd3b6f0e76fdfb21e87b1404bc81cbc41f646c78a3
M12.3 physical multi-tick/recurrent suite completed successfully.
```

The loop also visibly alternated recurrent queue banks on successive ticks while consuming one recurrent event and routing one new recurrent event per tick after the initial external stimulus. This provides direct physical evidence of the M09/M10 next-tick-only recurrence and double-buffered queue contract across repeated stateful execution.

#### Pass boundary

**Achieved.** Every directed M12.3 multi-tick/recurrent workload matches the independent Python FPGA-v1 golden trace exactly at every compared committed tick. The separate recurrent-loop reset/replay reproduces the same six-tick physical trace byte-for-byte after an independent programming/reset session. M12.3 therefore establishes that the FPGA behaves as a deterministic stateful neuromorphic processor model across repeated ticks, recurrent queue swaps, event ordering, fan-in/fan-out, multiplicity, quiescence, and state-history behavior.

#### Detailed design record

See `Neuromorphic Digital Twin/docs/M12_3_PHYSICAL_CONFORMANCE.md` for the corpus, evidence boundary, host/FPGA execution path, physical completion markers, replay hash, and interpretation.
'''
text = text[:start] + replacement + text[end:]
path.write_text(text, encoding="utf-8")

record = root / "Neuromorphic Digital Twin" / "docs" / "M12_3_PHYSICAL_CONFORMANCE.md"
record.write_text('''# M12.3 Physical Multi-Tick and Recurrent Conformance

## Status

Complete on the physical KV260 on 2026-09-07.

M12.3 extends the exact one-tick physical equivalence established in M12.2 into stateful execution across repeated algorithmic ticks. The goal is to prove that recurrent queues, state history, event ordering, and reset/replay behavior remain exactly aligned with the independent Python FPGA-v1 golden model.

## Evidence boundary

The physical FPGA is not given expected outputs. The source-controlled Python generator produces two distinct classes of artifact:

1. host-side Python-golden committed-tick traces used only for differential comparison; and
2. FPGA-visible input images containing static configuration plus the per-tick external-event schedule.

No recurrent-event schedule and no expected state/spike/queue arrays are present in FPGA-visible generated source. Recurrent events consumed on tick `t+1` must therefore have been produced by the FPGA's own spike-routing and double-buffered queue logic on tick `t`.

The physical evidence chain is:

```text
Python scenario + input image
          ↓
physical FPGA host-stepped execution
          ↓
immutable post-commit trace window every tick
          ↓
JTAG/VIO machine-readable JSON capture
          ↓
exact Python field-by-field differential
```

## Directed corpus

The frozen M12.3 corpus contains 10 scenarios totaling 40 committed ticks:

1. `feedforward-recurrent-chain`
2. `self-recurrent-oscillator`
3. `two-neuron-recurrent-loop`
4. `recurrent-fanout`
5. `recurrent-fanin`
6. `same-target-recurrent-multiplicity`
7. `external-plus-recurrent-same-tick`
8. `simultaneous-routing-order`
9. `quiescence-then-renewed-input`
10. `decay-refractory-history`

Together they cover next-tick recurrence, repeated queue-bank swaps, loops, fan-in/fan-out, same-target multiplicity, simultaneous routing order, mixed external/recurrent input, quiescence/restart, and multi-tick state history.

## Physical execution and observability

The M12.3 capture shell reuses the validated M11.5 computational core, the M12.1 physical trace boundary, and the M12.2 synchronous recurrent-bank readback correction. One selected scenario is loaded and reset, then each host `capture_step` executes exactly one algorithmic tick. The shell pauses after commit so the host can capture the complete immutable observation before the next tick's external events are loaded.

For every committed tick the host records and compares:

- architectural tick;
- external input events;
- consumed recurrent input events;
- signed-64 per-neuron synaptic accumulation;
- packed neuron state before and after the tick;
- spike flags;
- newly routed recurrent output events;
- active recurrent queue bank and counts for both banks;
- core fault state and code.

## Main physical result

The complete directed physical suite succeeded on the KV260:

```text
M12.3 physical directed multi-tick suite capture completed successfully: cases=10 ticks=40
M12.3 exact physical multi-tick differential passed: cases=10 ticks=40 mismatches=0
```

This means all 40 committed physical ticks matched the independent Python FPGA-v1 expectation exactly across every compared field.

## Reset/replay closure

Case 02, `two-neuron-recurrent-loop`, is the reset/replay anchor. After the main suite, the Hardware Manager flow starts a separate programming/reset session and captures the six-tick loop again. Both the original and replay captures must independently pass the Python differential before they are compared to each other.

The physical replay succeeded:

```text
M12.3 targeted case PASS: 02 two-neuron-recurrent-loop ticks=6 mismatches=0
M12.3 reset/replay passed: case=02 name=two-neuron-recurrent-loop ticks=6 semantic_exact=1 first_sha256=1d261d6d4a52e37a95a3dfdd3b6f0e76fdfb21e87b1404bc81cbc41f646c78a3 replay_sha256=1d261d6d4a52e37a95a3dfdd3b6f0e76fdfb21e87b1404bc81cbc41f646c78a3
M12.3 physical multi-tick/recurrent suite completed successfully.
```

The two six-tick serialized physical artifacts are byte-identical, not merely semantically equivalent.

During the loop, after the initial external stimulus, every subsequent tick consumed one recurrent event and routed one new recurrent event. The active recurrent bank alternated on each tick, directly exercising the double-buffered next-tick queue contract over repeated stateful execution.

## Interpretation

M12.3 provides stronger evidence than a final-state comparison. A same-tick recurrence error, incorrect queue-bank swap, lost/duplicated routed event, routing-order change, state-history divergence, or reset/replay defect would appear at the first affected committed tick and fail the exact differential.

The completion claim is therefore limited but strong: for the frozen 10-scenario directed M12.3 corpus, the physical K26 implementation reproduces the explicitly defined Python FPGA-v1 state transition and recurrent-routing contract exactly across 40 committed ticks, and the selected six-tick recurrent loop reproduces byte-identically after an independent programming/reset session.

M12.3 does not claim exhaustive physical validation of the entire supported configuration space. Broader deterministic stress belongs to M12.4, while final implementation characterization belongs to M12.5.

## Reproduction

After a successful M12.3 bitstream build and with the KV260 available to Vivado Hardware Manager:

```bash
cd "Neuromorphic Digital Twin/rtl/core_v1"
bash run_m12_3_hardware_suite.sh
```

The command preserves physical traces, per-case differential reports, the suite report, the independent reset/replay trace, and both Hardware Manager logs under `build/m12_3/`.
''', encoding="utf-8")
