from pathlib import Path

ROOT = Path('.')
RTL = ROOT / 'Neuromorphic Digital Twin' / 'rtl' / 'core_v1'
PROJECT = RTL / 'vivado' / 'create_m11_6_project.tcl'
SMOKE = RTL / 'm11_6_smoke_controller_v1.sv'
WRAPPER = RTL / 'm11_6_smoke_controller_bd_v1.v'
TEST = ROOT / 'Neuromorphic Digital Twin' / 'tests' / 'test_m11_6_bitstream_sources.py'
DOC = ROOT / 'Neuromorphic Digital Twin' / 'docs' / 'M11_6_BITSTREAM_HARDWARE_SMOKE.md'


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f'missing expected {label} block')
    return text.replace(old, new, 1)

# The smoke controller owns its own reset synchronizer for the computational FSM,
# but HLS reset is now generated by proc_sys_reset at the BD level so Vivado sees
# the correct ACTIVE_HIGH synchronous reset metadata.
text = SMOKE.read_text(encoding='utf-8')
text = replace_once(text,
    '    // Reset and scalar connection to packaged neuron_step_v1.\n    output logic                hls_ap_rst,\n    output logic                hls_ap_start,',
    '    // Scalar connection to packaged neuron_step_v1. HLS reset is supplied\n    // independently by the block-design proc_sys_reset instance.\n    output logic                hls_ap_start,',
    'smoke hls reset port')
text = replace_once(text,
    '    // Active-low VIO-controlled local reset is asynchronously asserted and\n    // synchronously released into the PL clock domain. The same synchronized\n    // reset is sent to the HLS IP so the complete smoke path shares one reset\n    // boundary without depending on PS software-managed fabric reset state.\n',
    '    // Active-low VIO-controlled local reset is asynchronously asserted and\n    // synchronously released into the PL clock domain. The block design derives\n    // both this active-low reset and the HLS active-high reset from the same\n    // proc_sys_reset instance, without depending on PS fabric-reset GPIO state.\n',
    'smoke reset comment')
text = replace_once(text,
    '    assign ap_rst     = reset_sync[1];\n    assign hls_ap_rst = ap_rst;\n',
    '    assign ap_rst = reset_sync[1];\n',
    'smoke hls reset assignment')
SMOKE.write_text(text, encoding='utf-8')

text = WRAPPER.read_text(encoding='utf-8')
text = replace_once(text,
    '    output wire                hls_ap_rst,\n    output wire                hls_ap_start,',
    '    output wire                hls_ap_start,',
    'wrapper hls reset port')
text = replace_once(text,
    '        .hls_ap_rst(hls_ap_rst),\n        .hls_ap_start(hls_ap_start),',
    '        .hls_ap_start(hls_ap_start),',
    'wrapper hls reset connection')
WRAPPER.write_text(text, encoding='utf-8')

text = PROJECT.read_text(encoding='utf-8')
text = replace_once(text,
    'foreach required_ip {xilinx.com:ip:zynq_ultra_ps_e:3.5 xilinx.com:ip:vio:3.0} {',
    'foreach required_ip {xilinx.com:ip:zynq_ultra_ps_e:3.5 xilinx.com:ip:vio:3.0 xilinx.com:ip:proc_sys_reset:5.0 xilinx.com:ip:xlconstant:1.1} {',
    'required IP list')
start = text.index('# Clock/reset boundary. The K26 PS reports its realizable PL0 frequency as')
end_marker = 'puts "M11.6 local reset/heartbeat boundary: reset=VIO smoke_resetn heartbeat=clock_heartbeat"\n'
end = text.index(end_marker, start) + len(end_marker)
new_block = '''# Clock/reset boundary. The K26 PS reports its realizable PL0 frequency as
# approximately 100 MHz (99,999,001 Hz with this board preset). Module Reference
# clock metadata inherits that propagated PS value. Reset ownership remains local
# to VIO, but proc_sys_reset converts the active-low VIO command into synchronized
# active-low smoke reset and synchronized active-high HLS ap_rst. The heartbeat is
# deliberately outside that reset path so Hardware Manager can prove pl_clk0 first.
set local_reset [create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_m11_6]
set_property -dict [list CONFIG.C_EXT_RESET_HIGH {0}] $local_reset
set const_one [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 const_one_m11_6]
set_property -dict [list CONFIG.CONST_WIDTH {1} CONFIG.CONST_VAL {1}] $const_one
set const_zero [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 const_zero_m11_6]
set_property -dict [list CONFIG.CONST_WIDTH {1} CONFIG.CONST_VAL {0}] $const_zero

connect_bd_net [get_bd_pins zynq_ultra_ps_e_0/pl_clk0] \\
    [get_bd_pins smoke_0/ap_clk] \\
    [get_bd_pins neuron_step_v1_0/ap_clk] \\
    [get_bd_pins vio_m11_6/clk] \\
    [get_bd_pins proc_sys_reset_m11_6/slowest_sync_clk]
connect_named_pair smoke_resetn vio_m11_6/probe_out1 proc_sys_reset_m11_6/ext_reset_in
connect_bd_net [get_bd_pins const_one_m11_6/dout] \\
    [get_bd_pins proc_sys_reset_m11_6/dcm_locked]
connect_bd_net [get_bd_pins const_zero_m11_6/dout] \\
    [get_bd_pins proc_sys_reset_m11_6/aux_reset_in] \\
    [get_bd_pins proc_sys_reset_m11_6/mb_debug_sys_rst]
connect_bd_net [get_bd_pins proc_sys_reset_m11_6/peripheral_aresetn] \\
    [get_bd_pins smoke_0/smoke_resetn]
connect_bd_net [get_bd_pins proc_sys_reset_m11_6/peripheral_reset] \\
    [get_bd_pins neuron_step_v1_0/ap_rst]
connect_named_pair clock_heartbeat smoke_0/clock_heartbeat vio_m11_6/probe_in13
puts "M11.6 local reset/heartbeat boundary: VIO reset -> proc_sys_reset; smoke=peripheral_aresetn HLS=peripheral_reset"
'''
text = text[:start] + new_block + text[end:]
PROJECT.write_text(text, encoding='utf-8')

text = TEST.read_text(encoding='utf-8')
text = replace_once(text,
    '    assert "assign hls_ap_rst = ap_rst;" in smoke\n',
    '    assert "hls_ap_rst" not in smoke\n',
    'test smoke HLS reset assertion')
text = replace_once(text,
    '    assert "xilinx.com:ip:proc_sys_reset:5.0" not in text\n    assert "xilinx.com:ip:xlconstant:1.1" not in text\n',
    '    assert "xilinx.com:ip:proc_sys_reset:5.0" in text\n    assert "xilinx.com:ip:xlconstant:1.1" in text\n',
    'test reset IP assertions')
text = replace_once(text,
    '    assert "connect_verified_pair hls_ap_rst ap_rst" in text\n    assert "connect_named_pair smoke_resetn" in text\n    assert "connect_named_pair clock_heartbeat" in text\n',
    '    assert "connect_verified_pair hls_ap_rst ap_rst" not in text\n    assert "connect_named_pair smoke_resetn vio_m11_6/probe_out1 proc_sys_reset_m11_6/ext_reset_in" in text\n    assert "proc_sys_reset_m11_6/peripheral_aresetn" in text\n    assert "proc_sys_reset_m11_6/peripheral_reset" in text\n    assert "[get_bd_pins neuron_step_v1_0/ap_rst]" in text\n    assert "connect_named_pair clock_heartbeat" in text\n',
    'test reset connectivity assertions')
TEST.write_text(text, encoding='utf-8')

text = DOC.read_text(encoding='utf-8')
text = replace_once(text,
    'The Zynq UltraScale+ processing-system block supplies only `pl_clk0` to the JTAG smoke shell. DDR and fixed-IO remain dedicated PS/SOM resources, and M11.6 adds no carrier-card PL `PACKAGE_PIN` assignments. The physical smoke no longer depends on software-managed `pl_resetn0`: VIO supplies an active-low `smoke_resetn`, the smoke controller asynchronously asserts and synchronously releases it in the PL clock domain, and that same synchronized state drives the packaged HLS `ap_rst`.\n',
    'The Zynq UltraScale+ processing-system block supplies only `pl_clk0` to the JTAG smoke shell. DDR and fixed-IO remain dedicated PS/SOM resources, and M11.6 adds no carrier-card PL `PACKAGE_PIN` assignments. The physical smoke no longer depends on software-managed `pl_resetn0`: VIO supplies the active-low local reset command to `proc_sys_reset`, whose synchronized `peripheral_aresetn` drives the smoke controller and synchronized active-high `peripheral_reset` drives packaged HLS `ap_rst`.\n',
    'doc reset architecture')
DOC.write_text(text, encoding='utf-8')

print('Patched M11.6 VIO-local reset through proc_sys_reset for Vivado reset metadata/polarity closure.')
