from pathlib import Path

path = Path("MILESTONES.md")
text = path.read_text(encoding="utf-8")
old = """### M12.2 — Exact single-tick Python-versus-FPGA differential validation\n\n**Status:** Planned\n\n#### Core goal\n\nProve that one complete physical FPGA algorithmic tick is exactly equivalent to the Python FPGA-v1 golden transition across a deliberately chosen directed corpus.\n\n#### Planned coverage\n"""
new = """### M12.2 — Exact single-tick Python-versus-FPGA differential validation\n\n**Status:** In progress  \n**Started:** 2026-09-02  \n**Repository evidence:** branch `agent/m12-2-single-tick-physical`\n\n#### Core goal\n\nProve that one complete physical FPGA algorithmic tick is exactly equivalent to the Python FPGA-v1 golden transition across a deliberately chosen directed corpus.\n\n#### Implementation in progress\n\n- A frozen 16-case directed Python corpus now independently generates packed FPGA load images and Python-golden physical-tick expectations across synaptic sign, E/I mixing, decay, saturation, threshold, refractory, multi-neuron/axon, multiplicity/empty-row, routing, and representative M08 weight-format boundaries.\n- FPGA-visible generated SystemVerilog contains only case inputs/load images. Python-golden expected outputs remain host-side and source-contract tests reject `M12_2_EXPECTED*` FPGA arrays.\n- A case-selectable physical shell reuses the unchanged M11.5 recurrent integrated core, unchanged M12.1 passive trace bridge, and the proven 26-input/6-output VIO shape. Arbitrary initial neuron state is deliberately written after architectural reset so saturation and refractory boundary probes survive into the tested tick.\n- The planned board flow programs one M12.2 bitstream, runs all 16 cases with a fresh architectural reset per case, writes one physical trace artifact per case, and performs exact host-side comparison of every physical trace field against Python.\n- The focused Python/source-contract gate passes. Routed Vivado 2025.2 implementation and physical KV260 zero-mismatch evidence remain the open completion gates.\n\n#### Planned coverage\n"""
if old not in text:
    raise SystemExit("M12.2 planned header not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
